### PR TITLE
#1222 Filters (Layered Navigation) - Add keyboard focus and adjust the way tab order should work

### LINKED ISSUE #1222: [feature]: Filters (Layered Navigation) - Add keyboard focus and the way tab order should work
As part of [#797](https://github.com/magento/pwa-studio/pull/797) - Layered navigation UI feature is added. But the keyboard focus and tab order does not work as expected.

Per meeting with [@soumya-ashok](https://github.com/soumya-ashok), these are the changes we've identified that need to be made:
* Focus on close button first
* “Escape” should always close modal no matter what depth/element is focused, should remember filter state
* Add outline/border to focused elements
* Add better aria labels to actionable for voiceover (get jimothy’s input)
* Kill tooltip or remove a11y arrow key from tooltip ie aria-ignore.
* Using space to select/unselect a color moves focus back to first color. Should remain on selected color/element. Apply treatment to other filter items
* Shift-tab on close should move focus to apply filters/resetfilters/ or last filter category. “Tab/focus trapping”
* On “apply filters” focus should move back to filter button
* On “reset filters” focus should move to first filter category button *not* the close button.

Additional:
* Make width 360px.
* Make expand from left instead of bottom.

Helpful Links:
* <https://webaim.org/techniques/keyboard/>

### PR DESCRIPTION
**Pull request by vasilii-b**
## Description

This PR adds the a11y changes to the Layered Navigation (Filters) modal on the category pages according to the specifications in #1222 .

## Related Issue

Closes #1222.

### Verification Stakeholders

@dpatil-magento @sirugh 

### Verification Steps

1. Go to any category page that contains products and has filter items.
2. Open the Filters modal.
3. Make sure Filters modal opens.
4. Make sure the modal's close (x) icon is focused.
5. From the keyboard, press the `Tab` key.
6. Make sure the focus switches to the next element. E.g filter item (Price).
7. Press the `Tab` key. Make sure the focus switches to the next filter item. E.g. "Color".
8. Press the `Space` key on the filter item "Color". The options should show. E.g. "Purple" and "Yellow"
9. Press the `Space` key. You should navigate through "Color" options.
10. Press the `Tab` key a few times until you focus the next filter item. E.g. "Material".
11. Press the `Tab` key a few more times until you focus the "Close" button again (that's when no filter option applied).

## Checklist

* I have added translations for new strings, if necessary.

### CODE REVIEW

**Comment by vasilii-b** [comment]
ℹ️ plan to proceed with the failed tests once the main changes are approved;

For now, will work on the spotted bug:
- after applying a filter item, the focus goes to the modal's "Close" icon.

**Comment by vasilii-b** [comment]
**update**

✅  The aforementioned bug has been addressed

**Comment by sirugh** [comment]
> ℹ️ plan to proceed with the failed tests once the main changes are approved;

Sounds good - I've moved the ticket to the "ux review" column. Once approved by UX it will move on to dev review.

**Comment by vasilii-b** [comment]
@sirugh may I ask to re-review this?
Added the latest updates according to the discussion in #1222 .
Thanks.

File: packages/peregrine/lib/talons/FilterModal/useFilterModal.js [hunk 1]
```diff
@@ -23,14 +23,15 @@ import DEFAULT_OPERATIONS from './filterModal.gql';
 export const useFilterModal = props => {
     const { filters } = props;
 
+    const DRAWER_NAME = 'filter';
```
Comment (sirugh) [inline packages/peregrine/lib/talons/FilterModal/useFilterModal.js:26]: Can move this `const` outside the function (above line 23).

File: packages/peregrine/lib/talons/FilterModal/useFilterModal.js [hunk 2]
```diff
@@ -123,11 +124,46 @@ export const useFilterModal = props => {
         }
     }, [filterKeys, filterState, history, isApplying, pathname, search]);
 
-    // on drawer toggle, read filter state from location
+    const handleOpen = useCallback(() => {
+        toggleDrawer(DRAWER_NAME);
+    }, [toggleDrawer]);
+
+    const handleClose = useCallback(() => {
+        closeDrawer(DRAWER_NAME);
```
Comment (sirugh) [inline packages/peregrine/lib/talons/FilterModal/useFilterModal.js:132]: `closeDrawer` does not take an argument.
```suggestion
        closeDrawer();
```

File: packages/venia-ui/lib/RootComponents/Category/categoryContent.js [hunk 3]
```diff
@@ -30,80 +38,74 @@ const CategoryContent = props => {
...
-        </Button>
+    const maybeFilterButtons = filters && filters.length ? (
+        <FilterModalOpenButton filters={filters} />
     ) : null;
 
+    const filtersModal = filters && filters.length ? (
+        <FilterModal filters={filters} />
+    ) : null;
+
+    const filtersAndTotalPagesPresent = !!(totalPagesFromData && filters);
```
Comment (sirugh) [inline packages/venia-ui/lib/RootComponents/Category/categoryContent.js:55]: If `filters` can be empty, should we also add the `filters.length` check here?

File: packages/venia-ui/lib/components/FilterModal/CurrentFilters/currentFilter.js [hunk 4]
```diff
@@ -9,15 +10,26 @@ import defaultClasses from './currentFilter.css';
...
+    const { formatMessage } = useIntl();
     const classes = mergeClasses(defaultClasses, props.classes);
 
     const handleClick = useCallback(() => {
         removeItem({ group, item });
     }, [group, item, removeItem]);
 
+    const ariaLabel = formatMessage(
+        {
+            id: 'filterModal.action.clearFilterItem.ariaLabel',
```
Comment (sirugh) [inline packages/venia-ui/lib/components/FilterModal/CurrentFilters/currentFilter.js:22]: Can you add this to [en_US.json](https://github.com/magento/pwa-studio/blob/develop/packages/venia-ui/i18n/en_US.json) please :)

File: packages/venia-ui/lib/components/FilterModal/CurrentFilters/currentFilter.js [hunk 5]
```diff
@@ -9,15 +10,26 @@ import defaultClasses from './currentFilter.css';
...
+            defaultMessage: 'Clear filter "{name}"'
```
Comment (sirugh) [inline packages/venia-ui/lib/components/FilterModal/CurrentFilters/currentFilter.js:23]: Also don't use variables in default messages. Just leave this as `Clear filter`. You can put the placeholder in the actual message in the json.

File: packages/venia-ui/lib/components/FilterModal/CurrentFilters/currentFilters.js [hunk 6]
```diff
@@ -33,7 +35,16 @@ const CurrentFilters = props => {
         return elements;
     }, [classes.item, filterState, removeItem]);
 
-    return <ul className={classes.root}>{filterElements}</ul>;
+    const currentFiltersAriaLabel = formatMessage({
+        id: 'filterModal.currentFilters.ariaLabel',
```
Comment (sirugh) [inline packages/venia-ui/lib/components/FilterModal/CurrentFilters/currentFilters.js:39]: Can you also add this to en_US.json.

File: packages/venia-ui/lib/components/FilterModal/FilterList/filterDefault.js [hunk 7]
```diff
@@ -8,8 +9,29 @@ import defaultClasses from './filterDefault.css';
...
+                  defaultMessage: 'Apply filter "{optionName}".'
+              },
+              {
+                  optionName: label
+              }
+          )
+        : formatMessage(
+              {
+                  id: 'filterModal.item.clearFilter',
+                  defaultMessage: 'Remove filter "{optionName}".'
```
Comment (sirugh) [inline packages/venia-ui/lib/components/FilterModal/FilterList/filterDefault.js:28]: Add to en_US.json and remove variable from default message.

File: packages/venia-ui/lib/components/FilterModal/FilterList/filterDefault.js [hunk 8]
```diff
@@ -8,8 +9,29 @@ import defaultClasses from './filterDefault.css';
...
     const { classes: propsClasses, isSelected, item, ...restProps } = props;
     const { label, value_index } = item || {};
+    const { formatMessage } = useIntl();
     const classes = mergeClasses(defaultClasses, propsClasses);
 
+    const ariaLabel = !isSelected
+        ? formatMessage(
+              {
+                  id: 'filterModal.item.applyFilter',
+                  defaultMessage: 'Apply filter "{optionName}".'
```
Comment (sirugh) [inline packages/venia-ui/lib/components/FilterModal/FilterList/filterDefault.js:19]: Add to en_US.json and remove variable from default message.

File: packages/venia-ui/lib/components/FilterModal/filterBlock.js [hunk 9]
```diff
@@ -20,26 +22,62 @@ const FilterBlock = props => {
...
+                  defaultMessage: 'Hide "{itemName}" filter item options.'
+              },
+              {
+                  itemName: name
+              }
+          )
+        : formatMessage(
+              {
+                  id: 'filterModal.item.showOptions',
+                  defaultMessage: 'Show "{itemName}" filter item options.'
```
Comment (sirugh) [inline packages/venia-ui/lib/components/FilterModal/filterBlock.js:48]: Add to en_US.json and remove variable from default message.

File: packages/venia-ui/lib/components/FilterModal/filterBlock.js [hunk 10]
```diff
@@ -20,26 +22,62 @@ const FilterBlock = props => {
...
+        {
+            itemName: name
+        }
+    );
+
+    const toggleItemOptionsAriaLabel = isExpanded
+        ? formatMessage(
+              {
+                  id: 'filterModal.item.hideOptions',
+                  defaultMessage: 'Hide "{itemName}" filter item options.'
```
Comment (sirugh) [inline packages/venia-ui/lib/components/FilterModal/filterBlock.js:39]: Add to en_US.json and remove variable from default message.

File: packages/venia-ui/lib/components/FilterModal/filterBlock.js [hunk 11]
```diff
@@ -20,26 +22,62 @@ const FilterBlock = props => {
         ? classes.list_expanded
         : classes.list_collapsed;
 
+    const itemAriaLabel = formatMessage(
+        {
+            id: 'filterModal.item.ariaLabel',
+            defaultMessage: 'Filter products by "{itemName}".'
```
Comment (sirugh) [inline packages/venia-ui/lib/components/FilterModal/filterBlock.js:28]: Add to en_US.json and remove variable from default message.

File: packages/venia-ui/lib/components/FilterModal/filterBlock.js [hunk 12]
```diff
@@ -20,26 +22,62 @@ const FilterBlock = props => {
...
+              {
+                  id: 'filterModal.item.showOptions',
+                  defaultMessage: 'Show "{itemName}" filter item options.'
+              },
+              {
+                  itemName: name
+              }
+          );
+
+    const filterItemOptions = isExpanded && (
```
Comment (sirugh) [inline packages/venia-ui/lib/components/FilterModal/filterBlock.js:55]: It seems the `listClass` handles the visibility. Is there a reason we should add this extra check? I'd stick with one or the other (probably just class) unless there are a11y implications to having a mounted, but invisible component.

File: packages/venia-ui/lib/components/FilterModal/filterFooter.js [hunk 13]
```diff
@@ -9,19 +9,27 @@ import defaultClasses from './filterFooter.css';
...
 const FilterFooter = props => {
     const { applyFilters, hasFilters, isOpen } = props;
+    const { formatMessage } = useIntl();
     const { touched } = useFilterFooter({
         hasFilters,
         isOpen
     });
     const classes = mergeClasses(defaultClasses, props.classes);
+    const buttonLabel = formatMessage({
+        id: 'filterFooter.results',
```
Comment (sirugh) [inline packages/venia-ui/lib/components/FilterModal/filterFooter.js:19]: Please add to en_US.json :)

File: packages/venia-ui/lib/components/FilterModal/filterModal.js [hunk 14]
```diff
@@ -55,9 +58,28 @@ const FilterModal = props => {
...
+
+    const closeAriaLabel = formatMessage({
+        id: 'filterModal.filters.close.ariaLabel',
+        defaultMessage: 'Close filters popup.'
+    });
+
+    const clearAllAriaLabel = formatMessage({
+        id: 'filterModal.action.clearAll.ariaLabel',
+        defaultMessage: 'Clear all applied filters'
+    });
```
Comment (sirugh) [inline packages/venia-ui/lib/components/FilterModal/filterModal.js:74]: Add messages to en_US.json.

File: packages/venia-ui/lib/RootComponents/Category/categoryContent.js [hunk 15]
```diff
@@ -30,80 +38,74 @@ const CategoryContent = props => {
...
-        ) : null;
-
-    // If you want to defer the loading of the FilterModal until user interaction
-    // (hover, focus, click), simply add the talon's `loadFilters` prop as
-    // part of the conditional here.
-    const modal = filters ? <FilterModal filters={filters} /> : null;
+    const maybeSortContainer = <SortedByContainer
+        shouldDisplay={filtersAndTotalPagesPresent}
+        currentSort={currentSort}
+    />;
```
Comment (sirugh) [inline packages/venia-ui/lib/RootComponents/Category/categoryContent.js:65]: The pattern we use in the repo is to do a conditional render rather than a prop used by the component. This is just a choice to leave render responsibility to the parent. Please swap this for the original pattern.

```suggestion
    const maybeSortContainer = filtersAndTotalPagesPresent ? <SortedByContainer
        currentSort={currentSort}
    /> : null;
```

File: packages/venia-ui/lib/components/SearchPage/searchPage.js [hunk 16]
```diff
@@ -48,71 +58,54 @@ const SearchPage = props => {
...
-            <span className={classes.sortText}>
-                <FormattedMessage
-                    id={currentSort.sortId}
-                    defaultMessage={currentSort.sortText}
-                />
-            </span>
-        </span>
-    ) : null;
+    const maybeSortContainer = <SortedByContainer
+        shouldDisplay={!!productsCount}
```
Comment (sirugh) [inline packages/venia-ui/lib/components/SearchPage/searchPage.js:106]: Same here re: conditional render.

**Review by sirugh — CHANGES_REQUESTED** [review]
Good work! This is close. Let me know if you have any questions about feedback. Also please run lint/prettier when you can. And we will need to fix tests at some point, but that can wait until it gets through the initial review (usually).

File: packages/venia-ui/lib/components/FilterModal/filterBlock.js (hunk 12 above)
Comment (vasilii-b) [reply packages/venia-ui/lib/components/FilterModal/filterBlock.js:55]: Thanks for the question, @sirugh.
The `isExpanded` check is necessary for the a11y. Here is the use case:

Filter item open/close

Please let me know whenever you think that's not necessary.
Thanks.

Comment (sirugh) [reply packages/venia-ui/lib/components/FilterModal/filterBlock.js:55]: What makes it necessary for a11y? Can't quite tell in the gif.

File: packages/venia-ui/i18n/en_US.json [hunk 17]
```diff
@@ -398,5 +398,15 @@
...
+    "filterModal.action.clearFilterItem.ariaLabel": "Clear filter \"{name}\"",
+    "filterModal.currentFilters.ariaLabel": "Current Filters",
+    "filterModal.item.applyFilter": "Apply filter \"{optionName}\".",
+    "filterModal.item.clearFilter": "Remove filter \"{optionName}\".",
+    "filterModal.item.ariaLabel": "Filter products by \"{itemName}\"",
+    "filterModal.item.hideOptions": "Hide \"{itemName}\" filter item options.",
+    "filterModal.item.showOptions": "Show \"{itemName}\" filter item options.",
+    "filterModal.filters.ariaLabel": "Filters",
+    "filterModal.filters.close.ariaLabel": "Close filters popup.",
+    "filterModal.action.clearAll.ariaLabel": "Clear all applied filters"
```
Comment (sirugh) [inline packages/venia-ui/i18n/en_US.json:411]: These should be alphabetically sorted in this file. Please do so :)

Comment (vasilii-b) [reply packages/venia-ui/i18n/en_US.json:411]: Oh, didn't pay attention to that. Will do.

File: packages/venia-ui/lib/components/SearchPage/searchPage.js [hunk 18]
```diff
@@ -48,70 +51,52 @@ const SearchPage = props => {
...
-                </section>
-                <section className={classes.pagination}>
-                    <Pagination pageControl={pageControl} />
-                </section>
-            </Fragment>
-        );
-    }
-
-    const totalCount = data.products.total_count || 0;
+        if (data.products.items.length === 0) {
```
Comment (sirugh) [inline packages/venia-ui/lib/components/SearchPage/searchPage.js:55]: Previously it was not possible to hit this conditional if data is falsy, but now it technically can. I don't know how likely it is but should we guard against it with a `return null`?

File: packages/venia-ui/lib/components/FilterModal/filterBlock.js (hunk 12 above)
Comment (vasilii-b) [reply packages/venia-ui/lib/components/FilterModal/filterBlock.js:55]: I think I've got your point now. Thanks.

Comment (vasilii-b) [reply packages/venia-ui/lib/components/FilterModal/filterBlock.js:55]: I was looking at the wrong part of the code. My bad.

File: packages/venia-ui/lib/components/FilterModal/filterBlock.js [hunk 19]
```diff
@@ -20,26 +22,62 @@ const FilterBlock = props => {
...
+    const filterItemOptions = (
+        <Form className={listClass}>
+            <FilterList
+                filterApi={filterApi}
+                filterState={filterState}
+                group={group}
+                items={items}
+            />
+        </Form>
+    );
```
Comment (sirugh) [inline packages/venia-ui/lib/components/FilterModal/filterBlock.js:64]: You can just put this back where it was on line 35 (now 80)

**Review by sirugh — DISMISSED** [review]
Looks like I missed some things in my initial review.

Also, how comfortable are you with writing/updating some tests?

File: packages/venia-ui/lib/components/FilterModal/filterBlock.js (hunk 12 above)
Comment (vasilii-b) [reply packages/venia-ui/lib/components/FilterModal/filterBlock.js]: So I've re-tested the implementation (the issue goal) after the changes.
This `isExpanded` has a huge impact. I've totally forgotten about it.
Here is the situation: when filter item options are rendered, using `TAB` key doesn't move the focus to the next filter item.


@sirugh Should we keep unmounting the filter item options? What do you suggest here?
Thanks.

**Comment by vasilii-b** [comment]
> Also, how comfortable are you with writing/updating some tests?

@sirugh I'll try to figure out what's going on. Never did it before.

**Comment by sirugh** [comment]
OK, let me know if you need help. Also, I think there might be a few comments that didn't get addressed yet. Have you pushed all your changes? We'd like to get this wrapped up so we can merge with the incoming desktop filters PR.

**Comment by vasilii-b** [comment]
Hi @sirugh ,
I have some changes still not pushed to the repo.

**Comment by sirugh** [comment]
@vasilii-b just checking in - anything I can do to help here?

**Comment by vasilii-b** [comment]
Hi @sirugh ,
Thanks for checking.
Currently, I do not have the required time for covering the remaining changes to be done. I could probably have more progress next week.
Is there any chance you can help with fixing the failed tests?
TIA

**Comment by sirugh** [comment]
> Is there any chance you can help with fixing the failed tests?

Sure, I'll give it a shot and address outstanding feedback (if any). Thanks for your work so far!

File: packages/venia-ui/lib/components/FilterModal/filterBlock.js (hunk 12 above)
Comment (sirugh) [reply packages/venia-ui/lib/components/FilterModal/filterBlock.js]: I don't think I quite follow what is happening or what the problem is. Could you jump on a call or slack thread with me sometime?

**Review by tjwiebell — DISMISSED** [review]
Commits 7d8eb6...27adec look good 👍

**Comment by dpatil-magento** [comment]
@sirugh Please check following - 
1. It has broken https://github.com/magento/pwa-studio/pull/2681
2. On Safari, after clearing a filter using space key, focus is going back to browser URL bar 
<a href="https://gyazo.com/245f3732b7443bdbf936253a1c744c95">Image from Gyazo</a>

**Comment by sirugh** [comment]
> It has broken #2681 (Nice to have unit test if possible :) )

I'll fix this.

**Comment by sirugh** [comment]
> On Safari, after clearing a filter using space key, focus is going back to browser URL bar

Interesting. I noted on Chrome that we also "lose" focus, though pressing tab goes to the top-most filter tab ie "Price". @vasilii-b do you have any ideas on how to fix this?

**Comment by dpatil-magento** [comment]
@sirugh When there are 0 filter results then sort button should not be displayed but its displaying. MFTF test failing, please check.

**Comment by sirugh** [comment]
> @sirugh When there are 0 filter results then sort button should not be displayed but its displaying. MFTF test failing, please check.

This is confusing, so we should show sort/filter button together, unless there are zero results in which case we should show the filter button but not the sort button?

**Comment by sirugh** [comment]
In my opinion we should ignore #2681 as rendering both together doesn't make sense.

File: packages/venia-ui/lib/RootComponents/Category/__tests__/categoryContent.spec.js [hunk 20]
```diff
@@ -51,53 +61,79 @@ const talonProps = {
...
-            sortProps={sortProps}
-            classes={classes}
-        />
-    );
+    const instance = createTestInstance(<CategoryContent {...props} />);
 
     expect(instance.toJSON()).toMatchSnapshot();
 });
+
+test('renders loading indicator if no data and  loading', () => {
```
Comment (tjwiebell) [inline packages/venia-ui/lib/RootComponents/Category/__tests__/categoryContent.spec.js:87]:
```suggestion
test('renders loading indicator if no data and loading', () => {
```

**Review by tjwiebell — DISMISSED** [review]
Looks good 👍  tiny bit of whitespace in test name, but ready for another round of QA.

**Review by tjwiebell — DISMISSED** [review]

**Comment by dpatil-magento** [comment]
QA Approved, ignored #2681

**Review by tjwiebell — APPROVED** [review]

**Comment by tkacheva** [comment]
Looks good from product perspective
