### PR TITLE
Change sort from relevance to position

### LINKED ISSUE #3124: [bug]: Default Category sort set to by position
**Describe the bug**

The category default sort order should align with the default back-end sort order.

**To reproduce**

1. open category page
2. note order of products

**Expected behavior**
Products ordered by position in ascending order 

**Screenshots**

image

image

**Possible solutions**

see PR

**Please complete the following device information:**

-   Device [e.g. iPhone6, PC, Mac, Pixel3]:
-   Browser [e.g. Chrome, Safari]:
-   Browser Version [e.g. 22]:
-   Magento Version [e.g Magento Commerce 2.4]:

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [ ] `venia-ui`
-   [ ] `pwa-buildpack`
-   [x] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

### PR DESCRIPTION
**Pull request by fooman**
## Description

Changed default sort from relevance to position

## Related Issue
Closes #3124

### Verification Steps
1. Open category page
2. adjust sort order of products in admin for categories
image
3. Lowest position products should show first

## Checklist

* I have added tests to cover my changes, if necessary.
* I have added translations for new strings, if necessary.
* I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Review by larsroettig — APPROVED** [review]
Good catch

File: packages/peregrine/lib/hooks/useSort.js [hunk 1]
```diff
@@ -2,9 +2,9 @@ import { useState } from 'react';
 
 const defaultSort = {
     sortText: 'Best Match',
-    sortId: 'sortItem.relevance',
-    sortAttribute: 'relevance',
-    sortDirection: 'DESC'
+    sortId: 'sortItem.position',
+    sortAttribute: 'position',
+    sortDirection: 'ASC'
```
Comment (sirugh) [inline packages/peregrine/lib/hooks/useSort.js:7]: This makes the default `position` but when you click the `Sort` dropdown there is no selection matching it. And then if you click "Best Match" it sets it back to `relevance`. Perhaps we should add an item in the [default props sort array](https://github.com/magento/pwa-studio/blob/develop/packages/venia-ui/lib/components/ProductSort/productSort.js#L114-L135). Should the `sortText` be "Position" then?

**Review by sirugh — DISMISSED** [review]

File: packages/peregrine/lib/hooks/useSort.js (hunk 1 above)
Comment (sirugh) [reply packages/peregrine/lib/hooks/useSort.js:8]: It was a minor change so I went ahead and did this :)

File: packages/venia-ui/lib/components/ProductSort/productSort.js [hunk 2]
```diff
@@ -113,6 +113,12 @@ ProductSort.propTypes = {
 
 ProductSort.defaultProps = {
     availableSortMethods: [
+        {
+            text: 'Position',
+            id: 'sortItem.position',
+            attribute: 'position',
+            sortDirection: 'ASC'
+        },
```
Comment (sirugh) [inline packages/venia-ui/lib/components/ProductSort/productSort.js:121]: One thought I just had was to rewrite the `useSort` hook to return both `current` and `available` sort rather than just be a state holder for current sort. Right now we have this odd coupling of sort methods with this array in `ProductSort` (which has a prop, so it can be passed the details from the parent).

**Review by jimbo — APPROVED** [review]
Seems fine.

**Comment by dpatil-magento** [comment]
QA Approved
