### PR TITLE
FilterModal talon

### LINKED ISSUE #1930: [bug]: Filters: unable to select fashion color filters
**Describe the bug**
User is unable to select Fashion colors filters. 

**To reproduce**
1. Go to any category and click on Filters button on `develop` https://magento.pwa-venia.com/
2. On Filters drawer expand Fashion Color section.
3. Click on any Fashion color. 

**Expected behavior**
Color should get selected as Filter.

**Expected behavior**
Colors are no more getting selected.

Note - Works fine in `4.0.0` release https://magento.pwa-venia.com/.  Broken in `develop` https://develop.pwa-venia.com/

**Screenshots**
**`develop`**

image

**`master` (4.0.0)**

image

### PR DESCRIPTION
**Pull request by sirugh**
## Description

Create Peregrine talons for the `FilterModal` component. As part of this work, refactor the component to use local state and hooks throughout, and improve its performance.

## Related Issue
Closes #1930 .

## Acceptance 
@sirugh 

### Verification Stakeholders
@dpatil-magento 

### Verification Steps
1. Navigate to a category page
2. Click `Filter` to open the filter modal (drawer)
3. Select some filters
4. Click `Apply Filters` to close the drawer and update the URL
5. Refresh the page
6. Reopen the filter modal and verify that the state remains correct
7. Click `Reset Filters` to clear all of the filters
8. Click the mask or the `X` to close the drawer and update the URL
9. Repeat this process on the search page

## Checklist
* I have updated the documentation accordingly, if necessary.
* I have added tests to cover my changes, if necessary.

### CODE REVIEW

File: packages/venia-ui/lib/components/FilterModal/FilterList/filterList.js [hunk 1]
```diff
@@ -59,38 +60,43 @@ const FilterList = props => {
...
 
     return (
-        <List
-            items={items}
-            getItemKey={({ value_string }) => `item-${id}-${value_string}`}
-            render={props => <ul className={layoutClass}>{props.children}</ul>}
-            renderItem={({ item }) => {
-                const isActive = isFilterSelected(item);
+        <Form>
+            <FilterSearch name="foo" />
```
Comment (sirugh) [inline packages/venia-ui/lib/components/FilterModal/FilterList/filterList.js]:
```suggestion
            <FilterSearch name={props.name} />
```

File: packages/peregrine/lib/talons/FilterModal/useFilterModal.js [hunk 2]
```diff
@@ -0,0 +1,176 @@
...
+            const nextSearch = getSearchFromState(
+                search,
+                filterKeys,
+                filterState
+            );
+
+            // write filter state to history
+            history.push({ pathname, search: nextSearch });
+            // close the drawer
+            closeDrawer();
```
Comment (sirugh) [inline packages/peregrine/lib/talons/FilterModal/useFilterModal.js]: Why is this effect a thing and not just what the `handleApply` callback does?

File: packages/peregrine/lib/talons/FilterModal/CurrentFilters/useCurrentFilters.js [hunk 3]
```diff
@@ -0,0 +1,24 @@
+import { useCallback } from 'react';
+import { useCatalogContext } from '@magento/peregrine/lib/context/catalog';
+
+export const useCurrentFilters = props => {
+    // TODO: Replace with useRouter.
+    const { history, location } = props;
+
+    const [{ chosenFilterOptions }, { removeFilter }] = useCatalogContext();
```
Comment (sirugh) [inline packages/peregrine/lib/talons/FilterModal/CurrentFilters/useCurrentFilters.js]: I noticed we don't hook up the `addFilter` from the catalog actions. Can the filter related actions be removed from catalog? I think we can use your new `removeItem` filter action.

Comment (jimbo) [reply packages/peregrine/lib/talons/FilterModal/CurrentFilters/useCurrentFilters.js]: Yes, that's correct. Filter state is no longer connected to Redux at all. I need to remove that stuff.

File: packages/peregrine/lib/talons/FilterModal/useFilterModal.js (hunk 2 above)
Comment (jimbo) [reply packages/peregrine/lib/talons/FilterModal/useFilterModal.js]: Well, a callback that did all of those things would end up being recreated whenever `filterState` changed. This way, the effect has the latest dependencies, but the callback never changes.

I do wonder about this pattern though. Do you think it's too indirect?

File: packages/peregrine/lib/talons/FilterModal/useFilterState.js [hunk 4]
```diff
@@ -0,0 +1,115 @@
...
+        case 'set items': {
+            return init(payload);
+        }
+    }
+};
+
+export const useFilterState = () => {
+    const [state, dispatch] = useReducer(reducer, null, init);
+
+    const addItem = useCallback(
```
[the remark this answers is not in the document]
Comment (jimbo) [reply packages/peregrine/lib/talons/FilterModal/useFilterState.js]: No, but it's an important part of the API. Our UI just happens to prefer `toggleItem`.

File: packages/peregrine/lib/talons/FilterModal/useFilterState.js [hunk 5]
```diff
@@ -0,0 +1,115 @@
...
+            return nextState;
+        }
+        case 'set items': {
+            return init(payload);
+        }
+    }
+};
+
+export const useFilterState = () => {
+    const [state, dispatch] = useReducer(reducer, null, init);
```
[the remark this answers is not in the document]
Comment (jimbo) [reply packages/peregrine/lib/talons/FilterModal/useFilterState.js]: Yes, I'll add it.

File: packages/venia-ui/lib/components/FilterModal/FilterFooter/filterFooter.js [hunk 6]
```diff
@@ -1,81 +1,45 @@
...
+    const handleApplyClick = useCallback(() => {
+        applyFilters();
+    }, [applyFilters]);
 
-    const applyButtonClass = areOptionsPristine
-        ? classes.applyButtonDisabled
-        : classes.applyButton;
+    const handleResetClick = useCallback(() => {
+        clear();
+        applyFilters();
```
[the remark this answers is not in the document]
Comment (jimbo) [reply packages/venia-ui/lib/components/FilterModal/FilterFooter/filterFooter.js]: Yes, I meant to bring this up. This happens because `history.push()` and `closeDrawer()` are part of the same callback/effect now. We have to persist to the URL after resetting the filters or else the reset will be lost if they click the mask, and since I'm invoking the callback/effect to persist to the URL, it's also closing the drawer.

I'll see what happens if I rework the callback/effect.

File: packages/peregrine/lib/talons/FilterModal/useFilterModal.js (hunk 2 above)
Comment (sirugh) [reply packages/peregrine/lib/talons/FilterModal/useFilterModal.js]: Aside from readability I'm not sure there's a drawback to this method. It's just tough to parse at first but I guess the alternative would be to pass state directly to the callback which means _something_ has to be aware of state.

File: packages/venia-ui/lib/components/FilterModal/FilterFooter/filterFooter.js (hunk 6 above)
[the remark this answers is not in the document]
Comment (jimbo) [reply packages/venia-ui/lib/components/FilterModal/FilterFooter/filterFooter.js]: This has been fixed.

File: packages/peregrine/lib/talons/FilterModal/useFilterModal.js (hunk 2 above)
Comment (jimbo) [reply packages/peregrine/lib/talons/FilterModal/useFilterModal.js]: This pattern really is necessary. There are alternatives, such as passing state around or accessing it through a ref, but I think this is the cleanest one so far. We can always revisit, since this isn't a totally unique case.

File: packages/peregrine/lib/talons/FilterModal/CurrentFilters/useCurrentFilters.js (hunk 3 above)
Comment (jimbo) [reply packages/peregrine/lib/talons/FilterModal/CurrentFilters/useCurrentFilters.js]: All references to Redux state have been removed. I also removed all of the effects that formerly had to check for filter params.

**Comment by jimbo** [comment]
For now, I've decided not to make talons for the last child components here, `CurrentFilters` and `FilterList`, at least for now. Right now, making talons for them would make them less efficient, and in the latter case that might actually matter. Making components for them will have to be a separate story that has performance as part of the AC.

File: packages/venia-ui/lib/components/FilterModal/filterFooter.js [hunk 7]
```diff
@@ -0,0 +1,37 @@
...
+    const { applyFilters, hasFilters, resetFilters } = props;
+    const classes = mergeClasses(defaultClasses, props.classes);
+
+    return (
+        <div className={classes.root}>
+            <Button disabled={!hasFilters} onClick={resetFilters}>
+                {'Reset Filters'}
+            </Button>
+            <Button
+                disabled={!hasFilters}
```
Comment (sirugh) [inline packages/venia-ui/lib/components/FilterModal/filterFooter.js]: If I toggle a filter and click `Apply Filters`, but then want to clear it (by toggling it again or clicking the `x`) without clicking "reset", how do I do that? Right now if you cannot "apply" an empty set of filters but I would assume it would allow it. This behavior is present on develop so we don't have to change it but it jumped out as a weird UX when I did it.

File: packages/venia-ui/lib/components/ProductOptions/tile.css [hunk 8]
```diff
@@ -3,8 +3,6 @@
     border: 1px solid rgb(var(--venia-text));
     border-radius: 2px;
     height: 3rem;
```
Comment (sirugh) [inline packages/venia-ui/lib/components/ProductOptions/tile.css]: Make sure to fix the media query that is busted with the 2rem height :o

Comment (jimbo) [reply packages/venia-ui/lib/components/ProductOptions/tile.css]: Also fixed.

File: packages/venia-ui/lib/components/FilterModal/FilterList/filterList.js [hunk 9]
```diff
@@ -1,111 +1,86 @@
...
-import { compose } from 'redux';
-import { array, bool, object, shape, string } from 'prop-types';
+import React, { Fragment, Suspense, lazy, useMemo } from 'react';
+import { array, bool, shape, string } from 'prop-types';
+import { useFieldState } from 'informed';
+import setValidator from '@magento/peregrine/lib/validators/set';
+
 import { mergeClasses } from '../../../classify';
-import { withRouter } from 'react-router-dom';
+import FilterItem from './FilterItem';
```
Comment (sirugh) [inline packages/venia-ui/lib/components/FilterModal/FilterList/filterList.js]:
```suggestion
import FilterItem from './filterItem';
```

File: packages/venia-ui/lib/components/FilterModal/filterBlock.js [hunk 10]
```diff
@@ -1,118 +1,55 @@
...
-export default classify(defaultClasses)(FilterBlock);
+const FilterBlock = props => {
+    const { filterApi, filterState, group, items, name } = props;
+    const talonProps = useFilterBlock({ group });
+    const { handleClick, isExpanded, isSwatch } = talonProps;
+    const iconSrc = isExpanded ? ArrowUp : ArrowDown;
+    const classes = mergeClasses(defaultClasses, props.classes);
+
+    const listProps = { filterApi, filterState, group, isSwatch, items, name };
+    const listElement = isExpanded ? <FilterList {...listProps} /> : null;
```
Comment (sirugh) [inline packages/venia-ui/lib/components/FilterModal/filterBlock.js]: Previously we were using CSS to hide the list. I did a little performance check and it takes 0.2ms to render the list on my mac.

It's _just_ enough that I noticed it. Not sure if you want to address that in the PR but it's something of note.

Comment (jimbo) [reply packages/venia-ui/lib/components/FilterModal/filterBlock.js]: Fixed it anyway. 👍

**Comment by dpatil-magento** [comment]
@jimbo Two UX things :
1. `Apply Filters` button is enabled by default.  It should be disabled. (Works in `develop` and `master`)
2. When you apply any filter and open filter overlay again > the filter sub section is expanded.  It should be collapsed. (Works in `master`  broken already in `develop`)

This PR - https://pr-1884.pwa-venia.com/
`develop` - https://develop.pwa-venia.com/
`master` - https://magento.pwa-venia.com/

**Comment by jimbo** [comment]
> `Apply Filters` button is enabled by default.  It should be disabled. (Works in `develop` and `master`)

This isn't quite true, though it does differ from live. To be precise, `Apply Filters` is disabled at first, but it becomes enabled and stays enabled once the form has been touched (i.e., once any filter has been changed). While this may be different from live, it's an intentional, necessary improvement here.

If `Apply Filters` were simply disabled whenever there were no filters selected in the form, the user would be unable to click `Apply Filters` after clicking `Reset Filters`.

> When you apply any filter and open filter overlay again, the filter sub section is expanded.  It should be collapsed. (Works in `master`  broken already in `develop`)

This is also different from live but not quite true. To be precise, the state of the filter modal is preserved while closed (like all other drawers in the app, actually), so any filter blocks that are expanded when the modal is closed will remain expanded when the modal is reopened. (If the user were to collapse a filter block before clicking `Apply Filters`, it would still be collapsed when reopening the modal.)

This is also an intentional, necessary improvement.

**Comment by jimbo** [comment]
> To be precise, `Apply Filters` is disabled at first, but it becomes enabled and stays enabled once the form has been touched (i.e., once any filter has been changed).

I did notice, though, that the `touched` state was not being reset to `false` when the modal was closed. This has been fixed. When reopening the modal, `Apply Filters` will now be disabled if there are no selected filters, or enabled if there are selected filters.

**Comment by sirugh** [comment]
Nice fix. 👍 from me

**Comment by abelyanvahe** [comment]
@sirugh  Hi. So I see that you moved the state to local state. But if you remember, the getCategory query happens in the category component, which is outside the FilterModal component. So How you are going to get the filters there in order to send it with the getCategory query? 
In the previous version, I could easily get it from Redux via context, but now I don't see any ways. 
Thanks in advance.

**Comment by sirugh** [comment]
@abelyanvahe good point. Can you open an issue with your concern and ping @jimbo as he may have some input :) We can discuss there.

**Comment by abelyanvahe** [comment]
OK Sure. Will do now.
