### PR TITLE
Fixed #1919 Product price is not changing while changing configurable options

### LINKED ISSUE #1919: Product price is not changing while changing configurable options
**Describe the bug**
Product price is not changing while changing configurable options

**To reproduce**
1. Go to pwa-studio home page
2. Click on category available
3. Click on any config product which has multiple options with different prices 
4.choose the differnt options one by one 

**Expected behavior**
The product price should change with the options 

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

### PR DESCRIPTION
**Pull request by shikhamis11**
Fixed #1919 Product price is not changing while changing configurable options

**To reproduce**

    Go to pwa-studio home page
    Click on category available
    Click on any config product which has multiple options with different prices
    4.choose the differnt options one by one

**Expected behavior**
The product price should change with the options

## Related Issue

Closes #1919

### CODE REVIEW

**Comment by shikhamis11** [comment]
hi @sirugh 
as per discussion over Pr #1920 . I have updated the changes with talons 
Please review this thanks

File: packages/peregrine/lib/talons/ProductFullDetail/useProductFullDetail.js [hunk 1]
```diff
@@ -152,12 +154,24 @@ export const useProductFullDetail = props => {
         },
         [setQuantity]
     );
+    
+    const isConfigurable = isProductConfigurable(product);
+    let productPrice = product.price.regularPrice.amount;
+    if (isConfigurable) {
+        const item = findMatchingVariant({
```
Comment (sirugh) [inline packages/peregrine/lib/talons/ProductFullDetail/useProductFullDetail.js]: I'd like to see this follow the pattern we've used in this file already of using a memo to get some value:

```js
const productPrice = useMemo(
  () => getProductPrice(product, optionCodes, optionSelections)
)
```

The `getProductPrice` function could be another top-level utility, it would look similar to `getMediaGalleryEntries`:

```js
const getProductPrice = (product, optionCodes, optionSelections) => {
  let productPrice = product.price.regularPrice.amount;
  
  if (isProductConfigurable(product)) {
    const item = findMatchingVariant({
      optionCodes,
      optionSelections,
      variants
    });

    productPrice = item.product.price.regularPrice.amount;
  }
  
  return productPrice;
}
```

**Comment by circlesix** [comment]
I was able to get this working with this code:
```const getConfigPrice = (product, optionCodes, optionSelections) => {
    let value = [];
    const { variants } = product;
    const isConfigurable = isProductConfigurable(product);

    const optionsSelected =
        Array.from(optionSelections.values()).filter(value => !!value).length >
        0;

    if (!isConfigurable || !optionsSelected) {
        value = product.price.regularPrice.amount.value;
    } else {
        const item = findMatchingVariant({
            optionCodes,
            optionSelections,
            variants
        });
        value = item
            ? item.product.price.regularPrice.amount.value
            : product.price.regularPrice.amount.value;
    }

    return value;
};```

and then calling it inside `useProductFullDetail` with:
```const configPrice = useMemo(
        () => getConfigPrice(product, optionCodes, optionSelections),
        [product, optionCodes, optionSelections]
    );```
I'm sure there is some optimization that needs to happen there, but it's working right now.

**Comment by sirugh** [comment]
Nice! that may be the right way to do it instead of my suggestion. The fallback for the `optionsSelected` is important. If we have a configurable product but no options have been selected we should still display the default price (as we won't have a variant selected).

File: packages/peregrine/lib/talons/ProductFullDetail/useProductFullDetail.js [hunk 2]
```diff
@@ -214,3 +205,30 @@ export const useProductFullDetail = props => {
         quantity
     };
 };
+
+const getConfigPrice = (product, optionCodes, optionSelections) => {
```
Comment (sirugh) [inline packages/peregrine/lib/talons/ProductFullDetail/useProductFullDetail.js]: For consistency please put this function up next to the other helper functions in this file.

File: packages/peregrine/lib/talons/ProductFullDetail/useProductFullDetail.js [hunk 3]
```diff
@@ -200,3 +205,30 @@ export const useProductFullDetail = props => {
...
+    let value = [];
```
Comment (sirugh) [inline packages/peregrine/lib/talons/ProductFullDetail/useProductFullDetail.js]: This can just be `let value;` as it will get set later. Also an array as a default seems wrong anyways.
