### PR TITLE
[PWA-1776] MegaMenu hover refactor to close submenu when clicking on link

### LINKED ISSUE #3070: [bug]: When clicking a submenu in the mega the submenu won't close
**Describe the bug**

When a user clicks on a submenu item in the new mega menu the site navigates to the new page but the submenu stays open. When your submenu has more children this becomes very annoying.

(shame on me I knew this bug would surface and totally forgot to report it whilst the PR was open)

**To reproduce**

1. Hover over a menu item that has a submenu
1. Click on a submenu item
1. Page navigates
1. Menu stays open

**Expected behavior**

I'd expect the megaMenu to close on navigate as a reference check <https://www.eleganza.nl/] where i've fixed the issue

**Screenshots**

**Possible solutions**

I've solved it by toggling a new class that has the exact same styling except the hover state. Because this is a class with a different name/generated hash it the browser will remove the hover state.

**Debug Report**

 

**Please let us know what packages this bug is in regards to:**
 - [ ] `venia-concept`
 - [x] `venia-ui`
 - [ ] `pwa-buildpack`
 - [x] `peregrine`
 - [ ] `pwa-devdocs`
 - [ ] `upward-js`
 - [ ] `upward-spec`
 - [ > `create-pwa`

### PR DESCRIPTION
**Pull request by jeremycharron**
## Description

Refactor hover effect on MegaMenuItem component to use Javascript mouse and touch events instead of pure CSS.
This fixes the issue described below. The submenu was staying opened after clicking/touching a link in the submenu.
It makes use of existing accessibility code created to open submenu with keyboard arrows.
This solution has been tested on both mouse and touch devices such as a laptop with touch screen. 

## Related Issue

Closes #3070

## Acceptance

N/A

### Verification Stakeholders

N/A

### Specification

N/A

#### Test scenario(s) for direct fix/feature

1. Verify that submenu is closing after clicking a link in submenu with mouse.
2. On a touch device, verify that submenu is closing after pressing a link in the submenu

#### Test scenario(s) for any existing impacted features/areas

1. Verify that submenu is opening when hovering a menu item with the mouse
2. On a touch device, verify that the submenu is opening when pressing a menu item 
3. Verify that submenu is closing when removing mouse from menu item
4. On a touch device, verify that submenu is closing when pressing outside of the submenu
5. Verify that accessibility shortcuts (arrow up and down) are still working properly
6. Verify that links in submenu are still redirecting to proper category on both desktop and touch devices
7. Compare general behavior of menu with current production or develop version of menu

#### Is Browser/Device testing needed?

Yes, browser testing is needed as megaMenu and children UI components may be impacted on Chrome, Safari, Firefox, Edge
Yes, device testing is needed as megaMenu and children UI components may be impacted on desktop and touch devices.

#### Any ad-hoc/edge case scenarios that need to be considered?

No

## Breaking Changes (if any)

1. Hover effect is now in JS, which means old hover effect must be removed from CSS on implementations of PWA Studio
2. Rename handleCloseSubMenu function to handleSubMenuFocus for clarity in useMegaMenuItem.js

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by schensley** [comment]
@jeremycharron I have reviewed the PR instance and it looks like the bug has been fixed. Nice work. UX approved.

File: packages/peregrine/lib/talons/MegaMenu/useMegaMenuItem.js [hunk 1]
```diff
@@ -6,9 +6,12 @@ export const useMegaMenuItem = props => {
     const [isFocused, setIsFocused] = useState(false);
     const isActive = category.id === activeCategoryId;
 
-    const handleCloseSubMenu = useCallback(() => {
-        setIsFocused(false);
-    }, [setIsFocused]);
+    const handleMenuItemFocus = useCallback(
+        (state = false) => {
```
Comment (pedrochiossi) [inline packages/peregrine/lib/talons/MegaMenu/useMegaMenuItem.js:10]: Instead of using a state parameter here, I would suggest adding separate handlers for Blur state (`setisFocused(false)`) and Focus state (`setIsFocused(true)`).

**Review by pedrochiossi — CHANGES_REQUESTED** [review]

File: packages/peregrine/lib/talons/MegaMenu/useMegaMenuItem.js (hunk 1 above)
Comment (jeremycharron) [reply packages/peregrine/lib/talons/MegaMenu/useMegaMenuItem.js]: Fixed in commit #6088fa7

**Review by pedrochiossi — DISMISSED** [review]

**Review by pedrochiossi — DISMISSED** [review]

**Review by revanth0212 — COMMENTED** [review]
The PR description says there are a couple of potential breaking changes. Should we make this a major change instead of a minor (which is the current tag)?

**Comment by jeremycharron** [comment]
> The PR description says there are a couple of potential breaking changes. Should we make this a major change instead of a minor (which is the current tag)?

I was actually hesitating to put a major tag. 
Basically now that the hovering effect is done in JS, it means removing the pseudo-class in CSS.
My knowledge of the project is still limited, but I assume that someone updating preregrine but not venia-ui will have an issue. That's something important to document for sure.

**Comment by supernova-at** [comment]
Talon response objects are part of our Public API, so the removal of `handleCloseSubMenu` in [useMegaMenuItem](https://github.com/magento/pwa-studio/pull/3599/files?authenticity_token=v1p3q%2FOJ8eyc7Fyz%2BdwLPUH4GD0eu9rM9wwXDwsRWnK6p4DPIDcZc4h77nZKeNER3j8Sb57enBXoVDjKLGjb7w%3D%3D&file-filters%5B%5D=.js&file-filters%5B%5D=.snap#diff-f09cf61527771298b415e41e6afcb59027bde9c6a8a48ff199d1072e9956f436) is a breaking change and necessitates a `Major` version bump (https://semver.org/).

**Comment by jeremycharron** [comment]
`handleMenuItemBlur` was renamed back to `handleCloseSubMenu` to avoid breaking change.

**Comment by revanth0212** [comment]
The functionality looks good, cypress and jest good too. Ready to merge.

**Review by pedrochiossi — APPROVED** [review]
