### PR TITLE
Null check for element styling

### LINKED ISSUE #3013: Fix pagebuilder null check bug
**Describe the bug**

After pb v4.0.0, getting an error {code:Cannot} read property 'setAttribute' of null{code} when trying to retrieve a custom page built on pagebuilder. My suspicion is that custom CMS block are unable to render after upgrading pagebuilder to 4.0.0 

**To reproduce**

1. Go to localhost <ins> '/custom-page'
1. See error

**Expected behavior**

Custom CMS block should be able to work

**Screenshots**

image

**Debug Report**

 rimraf dist
Hash: 24f0505b6c73e6e5aba1
Version: webpack 4.38.0
Time: 16177ms
Built at: 02/15/2021 6:45:04 PM
                                                                              Asset        Size  Chunks                    Chunk Names
                                                                            ./sw.js    37.1 KiB          <emitted]         
                                                         14.3486212eaab89abe84da.js      22 KiB      14  [emitted]         
                                                         15.7374109b97e2fc3b2501.js    9.83 KiB      15  [emitted]         
                                                         16.c3b0c4add085dabc2893.js    10.6 KiB      16  [emitted]         
                                                         17.593ab22fc3a6b417ff4b.js    5.56 KiB      17  [emitted]         
                                                         18.2e992ec4345f206c034c.js    4.67 KiB      18  [emitted]         
                                                         19.7486b840993521942005.js      20 KiB      19  [emitted]         
                                                         20.75901a443b18a192749d.js    3.72 KiB      20  [emitted]         
                                                         21.e973bc07009a877cb3f1.js    1.72 KiB      21  [emitted]         
                                                         22.810421c14501aecfb1fd.js    1.59 KiB      22  [emitted]         
                                                         23.0384d92b648d24ec975b.js    2.36 KiB      23  [emitted]         
                                                         24.5bc0e471dd8dd7130ffe.js    2.89 KiB      24  [emitted]         
                                                         25.b23b6c1aeef2413a801c.js    2.18 KiB      25  [emitted]         
                                                         26.108865ea9be80088b5e9.js    1.19 KiB      26  [emitted]         
                                                         27.c468dba39fcca042fbc3.js   195 bytes      27  [emitted]         
                                                          3.7e93d0b6f2ab6ca428ac.js    27.4 KiB       3  [emitted]         
                                                          4.8e2fc7eb69ef3ad4d452.js    72.1 KiB       4  [emitted]         
                                                          5.c81605aa17368970619d.js    8.53 KiB       5  [emitted]         
                                  RootCmp*CMS_PAGE**default.50aff7b0ab8b8edb4b89.js    8.52 KiB       6  [emitted]         RootCmp_CMS*PAGE**default
                                  RootCmp*NOTFOUND__default.9ed0377ab4101f84d832.js    1.11 KiB       7  [emitted]         RootCmp_NOTFOUND_*default
                                                                  VeniaLogo-n77.svg    1.47 KiB          [emitted]         
                                                                asset-manifest.json    2.67 KiB          [emitted]         
                                                     client.f7bb40aa264b3a73fc0a.js     478 KiB       8  [emitted]  [big]  client
                                                 i18n-en*US.d17a6848d087b4af7f4b.js      20 KiB       9  [emitted]         i18n-en*US
                                                                         index.html    6.99 KiB          [emitted]         
                                                            noProductsFound-e9n.png    30.7 KiB          [emitted]         
                                                    runtime.22a6b91c7756fec94328.js    3.71 KiB      10  [emitted]         runtime
                                                       templates/category-shell.mst   474 bytes          [emitted]         
                                                       templates/close-document.mst    20 bytes          [emitted]         
                                                        templates/cmspage-shell.mst   480 bytes          [emitted]         
                                                       templates/critical-style.mst  1010 bytes          [emitted]         
                                                 templates/default-font-include.mst    5.08 KiB          [emitted]         
                                             templates/default-initial-contents.mst    92 bytes          [emitted]         
                                                        templates/generic-shell.mst   288 bytes          [emitted]         
                                                       templates/js-unavailable.mst   565 bytes          [emitted]         
                                                  templates/loading-this-entity.mst   208 bytes          [emitted]         
                                                       templates/notfound-shell.mst   652 bytes          [emitted]         
                                                            templates/open-body.mst    99 bytes          [emitted]         
                                                        templates/open-document.mst    1.35 KiB          [emitted]         
                                                        templates/product-shell.mst   488 bytes          [emitted]         
                                                         templates/seed-bundles.mst    90 bytes          [emitted]         
                                                                         upward.yml   907 bytes          [emitted]         
                                                    vendors.a5d93ac02766c1b97bb4.js     347 KiB       0  [emitted]  [big]  vendors
                          vendors<sub>RootCmp*CATEGORY__default.915ba6d1cb31c70351e8.js      17 KiB      11  [emitted]         vendors</sub>RootCmp_CATEGORY_*default
vendors<sub>RootCmp*CATEGORY__default</sub>RootCmp_CMS_PAGE__default.2bd205e22f43f0d46395.js      68 KiB       1  [emitted]         vendors<sub>RootCmp_CATEGORY**default</sub>RootCmp_CMS*PAGE**default
  vendors<sub>RootCmp*CATEGORY__default</sub>RootCmp_SEARCH**default.555cbf2c166e7e21c6f0.js    19.4 KiB       2  [emitted]         vendors<sub>RootCmp_CATEGORY**default</sub>RootCmp_SEARCH_*default
                           vendors<sub>RootCmp*PRODUCT__default.d37901ce122cd8b51080.js    68.5 KiB      12  [emitted]         vendors</sub>RootCmp_PRODUCT_*default
                            vendors<sub>RootCmp*SEARCH__default.616113b9ee5791d93aa1.js    16.7 KiB      13  [emitted]         vendors</sub>RootCmp_SEARCH_*default
                                                           venia-static/favicon.ico    1.18 KiB          [emitted]         
                                            venia-static/icons/apple-touch-icon.png    3.23 KiB          [emitted]         
                                            venia-static/icons/venia*circle*144.png    5.22 KiB          [emitted]         
                                            venia-static/icons/venia*circle*192.png     6.8 KiB          [emitted]         
                                            venia-static/icons/venia*circle*512.png    18.6 KiB          [emitted]         
                                          venia-static/icons/venia*maskable*512.png      31 KiB          [emitted]         
                                            venia-static/icons/venia*square*144.png    6.89 KiB          [emitted]         
                                            venia-static/icons/venia*square*192.png    10.8 KiB          [emitted]         
                                            venia-static/icons/venia*square*512.png    19.1 KiB          [emitted]         
                                             venia-static/icons/venia*square*57.png    1.23 KiB          [emitted]         
                                                         venia-static/manifest.json   850 bytes          [emitted]         
                                                            venia-static/robots.txt    23 bytes          [emitted]         
                                                       venia-static/veniaClosed.png    28.3 KiB          [emitted]         
Entrypoint client [big] = runtime.22a6b91c7756fec94328.js vendors.a5d93ac02766c1b97bb4.js client.f7bb40aa264b3a73fc0a.js
[0] multi (webpack)-inject-plugin/dist/webpack-inject-plugin.loader?id=webpack-inject-module-1 (webpack)-inject-plugin/dist/webpack-inject-plugin.loader?id=webpack-inject-module-2 ./src/index.js 52 bytes {8} [built]
[5I32] ./en_US.json 19.8 KiB {9} [built]
[5X6z] ./node_modules/@magento/venia-ui/lib/RootComponents/NotFound/index.js </ins> 1 modules 1.12 KiB {7} [built>
|    2 modules
<9teu] ./node_modules/@magento/venia-ui/lib/RootComponents/Category/index.js <ins> 9 modules 26 KiB {11} [built>
|    10 modules
<Dx</ins>2] ./node_modules/@magento/venia-ui/lib/RootComponents/CMS/index.js <ins> 8 modules 13.3 KiB {6} [built>
|    9 modules
<FASw] (webpack)-inject-plugin/dist/webpack-inject-plugin.loader.js?id=webpack-inject-module-1 1.38 KiB {8} [built]
[FEiY] ./node_modules/@magento/venia-ui/lib/RootComponents/Product/index.js </ins> 36 modules 79.7 KiB {12} [built>
|    37 modules
<H8<ins>m] ./node_modules/@apollo/client/utilities/index.js </ins> 18 modules 44.3 KiB {0} [built>
|    19 modules
<N6ZK] ./node_modules/@magento/venia-ui/lib/RootComponents/Search/index.js <ins> 3 modules 15.7 KiB {13} [built>
|    4 modules
<Q81g] ./node_modules/@apollo/client/link/retry/index.js </ins> 3 modules 6.33 KiB {0} [built>
|    4 modules
<SMaB] (webpack)-inject-plugin/dist/webpack-inject-plugin.loader.js?id=webpack-inject-module-2 410 bytes {8} [built]
[hqrM] ./src/drivers.js 303 bytes [built]
[lrJ8] ./node_modules/@magento/peregrine/lib/RestApi/index.js <ins> 4 modules 17.6 KiB {8} [built>
|    5 modules
<tjUo] ./src/index.js </ins> 95 modules 191 KiB {8} [built>
| ./src/index.js 4.31 KiB <built>
| ./src/store.js 598 bytes <built>
| ./src/registerSW.js 742 bytes <built>
| ./src/util/formatLocale.js 516 bytes <built>
|     <ins> 92 hidden modules
<yLpj] (webpack)/buildin/global.js 472 bytes {8} [built]
    </ins> 1022 hidden modules

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  vendors.a5d93ac02766c1b97bb4.js (347 KiB)
  client.f7bb40aa264b3a73fc0a.js (478 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  client (830 KiB)
      runtime.22a6b91c7756fec94328.js
      vendors.a5d93ac02766c1b97bb4.js
      client.f7bb40aa264b3a73fc0a.js

Child InjectManifest:
     1 asset
    Entrypoint InjectManifest = ./sw.js
    [0Gu<ins>] ./src/ServiceWorker/sw.js </ins> 90 modules 217 KiB {0} [built>
| ./src/ServiceWorker/sw.js 466 bytes <built>
| ./src/ServiceWorker/Utilities/messageHandler.js 5.07 KiB <built>
| ./src/ServiceWorker/setupWorkbox.js 1.21 KiB <built>
| ./src/ServiceWorker/registerRoutes.js 3.09 KiB <built>
| ./src/ServiceWorker/defaults.js 130 bytes <built>
| ./src/ServiceWorker/Utilities/imageCacheHandler.js 9.05 KiB <built>
| ./src/ServiceWorker/Utilities/routeHandler.js 485 bytes <built>
| ./src/ServiceWorker/Utilities/networkUtils.js 704 bytes <built>
|     <ins> 83 hidden modules
    <0bNL] ./src/ServiceWorker/registerMessageHandlers.js 88 bytes [built]
        </ins> 13 hidden modules
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [YuTi] (webpack)/buildin/module.js 497 bytes {0} [built]
    [orVB] ./node_modules/html-webpack-plugin/lib/loader.js!./template.html 8.34 KiB {0} [built]
    [yLpj] (webpack)/buildin/global.js 472 bytes {0} [built]
        + 1 hidden module
Done in 29.70s.

**Please complete the following device information:**

-   Device: PC
-   Browser: Chrome
-   Browser Version: 88
-   Magento Version [e.g Magento Commerce 2.4]:

[!-- Complete the following sections to help us apply appropriate labels! --]

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [yes] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ > `create-pwa`

### PR DESCRIPTION
**Pull request by rycastaneda**
Fixes for https://github.com/magento/pwa-studio/issues/3013

## Description

Null check for element styling

## Related Issue

Closes #3013

### Verification Steps

1. Go to a custom page built with pagebuilder with a custom CMS block
2. Verify that the page loads correctly without error

### CODE REVIEW

**Review by eug123 — DISMISSED** [review]

**Review by sirugh — APPROVED** [review]

File: packages/pagebuilder/lib/pagebuilder.js [hunk 1]
```diff
@@ -10,7 +10,7 @@ import parseStorageHtml from './parseStorageHtml';
  * @constructor
  */
 export default function PageBuilder({ html, classes }) {
-    const data = parseStorageHtml(html);
+    const data = useMemo(() => parseStorageHtml(html), [html]);
```
Comment (jimbo) [inline packages/pagebuilder/lib/pagebuilder.js:13]: Yikes, good change. 👍

**Review by jimbo — APPROVED** [review]
Thanks for the contribution, it makes sense to me. Will get this on our board.

**Comment by dpatil-magento** [comment]
QA Approved. 

@rycastaneda Please sign Adobe CLA https://github.com/magento/pwa-studio/pull/3016/checks?check_run_id=2071055563,  I won't be merge until the check turn green.
