### PR TITLE
Merge Carts on log in

### LINKED ISSUE #2190: [bug]: Call mergeCarts to merge guest and customer carts within customer login
**Describe the bug**
PWA does not merge `guest` and `customer` shopping carts.

**To reproduce**
**1.** As `guest`, add any product into shopping cart
**2.** Login as a registered `customer`
**3.** Verify customer's shipping cart

**Actual result**
Customer's cart **does not** contain a product which has been added into guest's cart

**Expected behavior**
Customer's cart contains a product which has been added into guest's cart.

**Screenshots**

**Additional context**

**Possible solutions**
We should use [mergeCarts](https://devdocs.magento.com/guides/v2.3/graphql/mutations/merge-carts.html) mutation query if visitor has added a product as guest into shopping cart and then it logs in as a customer.

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]:
 - OS [e.g. iOS8.1, Windows 10]:
 - Browser [e.g. Chrome, Safari]:
 - Browser Version [e.g. 22]:
 - Magento Version:
 - PWA Studio Version:
 - NPM version `npm -v`:
 - Node Version `node -v`:

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

### PR DESCRIPTION
**Pull request by dani97**
## Description
Cart Merge feature

## Related Issue

Closes #2190 

### Verification Stakeholders

@sirugh 
@tjwiebell 
### Verification Steps

1. Login and add products to cart
2. logout and add products as guest
3. Login again
4. cart should be merged with both list of products

## Checklist

* I have updated the documentation accordingly, if necessary.
* I have added tests to cover my changes, if necessary.

### CODE REVIEW

**Comment by dani97** [comment]
@sirugh today I noticed an unusual behaviour from this branch, so I'm testing this on venia.magento.com . Consider I have a logged in customer with items in cart, the cart is persisted in local storage via apollo connection Cart as mentioned here https://github.com/magento/pwa-studio/pull/2322.
The customer logs in the next day and his token is expired so he has is continuing as guest user, but the cart details and other stuff are persisted in browser cache. The minicart shows items are present but when we open it errors are thrown. When we add products to cart, the cart is not accessible by guest. I think the whole browser persistence cache needs to be reset after token is expired.
I
Screenshot from 2020-05-02 19-06-05
Screenshot from 2020-05-02 19-06-32

**Comment by dani97** [comment]
> @sirugh today I noticed an unusual behaviour from this branch, so I'm testing this on venia.magento.com . Consider I have a logged in customer with items in cart, the cart is persisted in local storage via apollo connection `Cart` as mentioned here #2322.
> The customer logs in the next day and his token is expired so he has is continuing as guest user, but the cart details and other stuff are persisted in browser cache. The minicart shows items are present but when we open it errors are thrown. When we add products to cart, the cart is not accessible as token is expired. When we login again, everything works fine.
> I think the whole browser persistence cache needs to be reset after token is expired.
> Screenshot from 2020-05-02 19-06-05
> Screenshot from 2020-05-02 19-06-32

This issue exists in 6.0 release as well. Just verified in https://venia.magento.com/

File: packages/peregrine/lib/store/reducers/cart.js [hunk 1]
```diff
@@ -28,12 +28,35 @@ const reducerMap = {
...
+            isLoading: true
+        };
+    },
     [actions.getDetails.request]: state => {
         return {
             ...state,
             isLoading: true
         };
     },
+    [actions.mergeCarts.receive]: (state, { payload, error }) => {
```
Comment (sirugh) [inline packages/peregrine/lib/store/reducers/cart.js:43]: Move the `request`/`receive` functions next to their counterparts. Right now you have request, request, receive, receive.

File: packages/peregrine/lib/store/reducers/cart.js [hunk 2]
```diff
@@ -28,12 +28,35 @@ const reducerMap = {
...
+        if (error) {
+            return {
+                ...state,
+                detailsError: payload,
```
Comment (sirugh) [inline packages/peregrine/lib/store/reducers/cart.js:47]: Define a new error property in the store for `mergeError` rather than re-using the `getDetails` property.

File: packages/peregrine/lib/store/actions/cart/asyncActions.js [hunk 3]
```diff
@@ -336,6 +336,52 @@ export const getCartDetails = payload => {
...
+            const { mergeCarts: details } = data;
+
+            dispatch(actions.mergeCarts.receive({ details }));
+        } catch (error) {
+            dispatch(actions.mergeCarts.receive(error));
+
+            const shouldResetCart = !error.networkError && isInvalidCart(error);
+            if (shouldResetCart) {
+                // Delete the cached ID from local storage.
+                await dispatch(removeCart());
```
Comment (sirugh) [inline packages/peregrine/lib/store/actions/cart/asyncActions.js:377]: We may have the same problem in #2378 here. Do you mind waiting for the fix? You could also just apply the change to the `isInvalidCart` function that I made in the PR.

File: packages/peregrine/lib/store/actions/cart/asyncActions.js [hunk 4]
```diff
@@ -336,6 +336,52 @@ export const getCartDetails = payload => {
...
+    async function thunk(dispatch) {
+        const { mergeCarts, fetchCartId } = payload;
+        const sourceCartId = await retrieveCartId();
+        try {
+            await dispatch(removeCart());
+            await dispatch(
+                createCart({
+                    fetchCartId
+                })
+            );
```
Comment (sirugh) [inline packages/peregrine/lib/store/actions/cart/asyncActions.js:349]: Why do you remove and create a cart immediately?

File: packages/peregrine/lib/store/actions/cart/asyncActions.js [hunk 5]
```diff
@@ -336,6 +336,52 @@ export const getCartDetails = payload => {
     };
 };
 
+export const retrieveAndMergeCarts = payload =>
```
Comment (sirugh) [inline packages/peregrine/lib/store/actions/cart/asyncActions.js:339]: Please add JSDoc here explaining what this function does.

File: packages/peregrine/lib/store/actions/cart/asyncActions.js [hunk 6]
```diff
@@ -336,6 +336,52 @@ export const getCartDetails = payload => {
...
+        try {
+            await dispatch(removeCart());
+            await dispatch(
+                createCart({
+                    fetchCartId
+                })
+            );
+        } catch (error) {
+            dispatch(actions.mergeCarts.receive(error));
+            return thunk(...arguments);
```
Comment (sirugh) [inline packages/peregrine/lib/store/actions/cart/asyncActions.js:352]: This will retry the operation right? Could this cause an infinite loop?

File: packages/peregrine/lib/store/actions/cart/asyncActions.js [hunk 7]
```diff
@@ -336,6 +336,52 @@ export const getCartDetails = payload => {
     };
 };
 
+export const retrieveAndMergeCarts = payload =>
+    async function thunk(dispatch) {
+        const { mergeCarts, fetchCartId } = payload;
+        const sourceCartId = await retrieveCartId();
+        try {
+            await dispatch(removeCart());
```
Comment (sirugh) [inline packages/peregrine/lib/store/actions/cart/asyncActions.js:344]: I see here that we have to remove/create to get the user's cart id as the destination. It wasn't clear at first, so please add some comments here explaining this.

File: packages/peregrine/lib/store/actions/cart/asyncActions.js [hunk 8]
```diff
@@ -336,6 +336,52 @@ export const getCartDetails = payload => {
...
+            );
+        } catch (error) {
+            dispatch(actions.mergeCarts.receive(error));
+            return thunk(...arguments);
+        }
+
+        try {
+            // errors can come from graphql and are not thrown
+            const destinationCartId = await retrieveCartId();
+            await dispatch(removeCart());
```
Comment (sirugh) [inline packages/peregrine/lib/store/actions/cart/asyncActions.js:358]: Why do you remove the cart? Can we just call `mergeCarts` and have the result overwrite the old data? I don't think we need to call the `remove` action here.

File: packages/peregrine/lib/talons/SignIn/useSignIn.js [hunk 9]
```diff
@@ -57,16 +59,13 @@ export const useSignIn = props => {
                 await setToken(token);
                 await getUserDetails({ fetchUserDetails });
 
-                // Then remove the old guest cart and get the cart id from gql.
-                // TODO: This logic may be replacable with mergeCart in 2.3.4
-                await removeCart();
+                await retrieveAndMergeCarts({
```
[the remark this answers is not in the document]
Comment (dani97) [reply packages/peregrine/lib/talons/SignIn/useSignIn.js:62]: sure I will work on that @sirugh

File: packages/peregrine/lib/store/actions/cart/asyncActions.js (hunk 5 above)
Comment (dani97) [reply packages/peregrine/lib/store/actions/cart/asyncActions.js:339]: sure

File: packages/peregrine/lib/store/actions/cart/asyncActions.js (hunk 6 above)
Comment (dani97) [reply packages/peregrine/lib/store/actions/cart/asyncActions.js:352]: I followed getDetails as example, I will work on this

File: packages/peregrine/lib/store/actions/cart/asyncActions.js (hunk 8 above)
Comment (dani97) [reply packages/peregrine/lib/store/actions/cart/asyncActions.js:358]: It didn't rewrite for me at some places, sure I will try removing this.

Comment (dani97) [reply packages/peregrine/lib/store/actions/cart/asyncActions.js:358]: Hey @sirugh can we use this example, to let mutation update cart ids
https://www.apollographql.com/docs/tutorial/mutations/#expose-apollo-client-with-useapolloclient

File: packages/peregrine/lib/talons/SignIn/useSignIn.js [hunk 10]
```diff
@@ -57,16 +59,13 @@ export const useSignIn = props => {
...
+                    fetchCartId,
+                    mergeCarts
+                });
 
                 await clearCartDataFromCache(apolloClient);
```
[the remark this answers is not in the document]
Comment (dani97) [reply packages/peregrine/lib/talons/SignIn/useSignIn.js:67]: Have to clear guest cart id, that is still present in apollo-cache-persist

[the remark this answers is not in the document]
Comment (dani97) [reply packages/peregrine/lib/talons/SignIn/useSignIn.js:67]: This affects cart-trigger component

**Comment by dani97** [comment]
@sirugh I have fixed the most of the comments and still the unnecessary `removeCart` and `clearCartDataFromCache` are in the code, if I remove them, the cart trigger component not reflects the value correctly but mini cart and other components works perfectly. I went through apollo docs and found [this example](https://www.apollographql.com/docs/tutorial/mutations/#expose-apollo-client-with-useapolloclient) to update cache after mutation is executed, can we use this pattern to refresh cache entries to avoid unnecessary `removeCart` and `clearCartDataFromCache`.

File: packages/peregrine/lib/store/actions/cart/asyncActions.js (hunk 6 above)
Comment (dani97) [reply packages/peregrine/lib/store/actions/cart/asyncActions.js]: removed retries

File: packages/peregrine/lib/store/reducers/cart.js (hunk 2 above)
Comment (dani97) [reply packages/peregrine/lib/store/reducers/cart.js]: fixed it.

**Comment by devops-pwa-codebuild** [comment]
**Performance Test Results**

The following fails have been reported by WebpageTest. These numbers indicates a possible performance issue with the PR which requires further manual testing to validate.

https://pr-2377.pwa-venia.com : LH Performance Expected 0.85 Actual 0.58, LH Best Practices Expected 1 Actual 0.92
https://pr-2377.pwa-venia.com/venia-tops.html : LH Performance Expected 0.75 Actual 0.35, LH Best Practices Expected 1 Actual 0.92
https://pr-2377.pwa-venia.com/valeria-two-layer-tank.html : LH Performance Expected 0.8 Actual 0.51, LH Accessibility Expected 0.9 Actual 0.89, LH Best Practices Expected 1 Actual 0.92

File: packages/peregrine/lib/store/actions/cart/asyncActions.js [hunk 11]
```diff
@@ -360,6 +360,50 @@ export const getCartDetails = payload => {
     };
 };
 
+/**
+ * Merges Guest cart with Logged in user's cart
+ *
+ * @param payload.mergeCarts {Object} merge carts mutation hook object
+ * @param payload.fetchCartId {Object} fetch cart id mutation hook object
+ */
+export const retrieveAndMergeCarts = payload =>
```
[the remark this answers is not in the document]
Comment (dani97) [reply packages/peregrine/lib/store/actions/cart/asyncActions.js:369]: there is already mergeCarts Mutation coming from payload, to differentiate I used this term.

File: packages/peregrine/lib/talons/CreateAccount/useCreateAccount.js [hunk 12]
```diff
@@ -91,16 +92,13 @@ export const useCreateAccount = props => {
                 await setToken(token);
                 await getUserDetails({ fetchUserDetails });
 
-                // Then remove the old guest cart and get the cart id from gql.
-                // TODO: This logic may be replacable with mergeCart in 2.3.4
-                await removeCart();
-
-                await clearCartDataFromCache(apolloClient);
```
[the remark this answers is not in the document]
Comment (sirugh) [reply packages/peregrine/lib/talons/CreateAccount/useCreateAccount.js:99]: The alternative, and what I just pushed, is to request all the necessary cart data in the merge response and allow the cache update to propagate.

File: packages/peregrine/lib/talons/SignIn/useSignIn.js [hunk 13]
```diff
@@ -57,16 +58,13 @@ export const useSignIn = props => {
                 await setToken(token);
                 await getUserDetails({ fetchUserDetails });
 
-                // Then remove the old guest cart and get the cart id from gql.
-                // TODO: This logic may be replacable with mergeCart in 2.3.4
-                await removeCart();
-
-                await clearCartDataFromCache(apolloClient);
```
[the remark this answers is not in the document]
Comment (sirugh) [reply packages/peregrine/lib/talons/SignIn/useSignIn.js:65]: Responded on the other comment :)

File: packages/venia-ui/lib/queries/mergeCarts.graphql [hunk 14]
```diff
@@ -0,0 +1,42 @@
...
+                    value_label
+                }
+            }
+        }
+        prices {
+            grand_total {
+                value
+                currency
+            }
+        }
```
[the remark this answers is not in the document]
Comment (sirugh) [reply packages/venia-ui/lib/queries/mergeCarts.graphql]: I've since updated this to use the relevant cart fragments.

File: packages/peregrine/lib/store/actions/cart/asyncActions.js [hunk 15]
```diff
@@ -360,6 +360,50 @@ export const getCartDetails = payload => {
...
+    async function thunk(dispatch) {
+        const { mergeCarts, fetchCartId } = payload;
+        const sourceCartId = await retrieveCartId();
+
+        try {
+            // remove guest cart id from local storage
+            await dispatch(removeCart());
```
[the remark this answers is not in the document]
Comment (sirugh) [reply packages/peregrine/lib/store/actions/cart/asyncActions.js:376]: We also need to clear cart data from apollo here.

File: packages/peregrine/lib/store/actions/cart/asyncActions.js [hunk 16]
```diff
@@ -360,6 +360,50 @@ export const getCartDetails = payload => {
...
+            // create customer cart
+            await dispatch(
+                createCart({
+                    fetchCartId
+                })
+            );
```
[the remark this answers is not in the document]
Comment (sirugh) [reply packages/peregrine/lib/store/actions/cart/asyncActions.js:382]: We might be able to do away with the async action for merging if in the sign in callback we:

1) Obtain a reference to guest cart id or "source id"
2) Clear all cart data from cache/redux
3) Query for `customerCart` to get "destination id"
4) Merge carts. Spread response through cache/redux.

This logic is basically what was written here in the action, but since we are going to be moving towards removing much of the cart slice it makes sense to try to do this in the talons. Moving it to the talon also allows us to directly call `clearCartDataFromCache` at the same time we call the `removeCart` action.

[the remark this answers is not in the document]
Comment (dani97) [reply packages/peregrine/lib/store/actions/cart/asyncActions.js:382]: @sirugh how to dispatch in talons, if any rewrite of async action to talon is done, can you share that?.

[the remark this answers is not in the document]
Comment (sirugh) [reply packages/peregrine/lib/store/actions/cart/asyncActions.js:382]: > how to dispatch in talons, if any rewrite of async action to talon is done, can you share that?.

Of course I can share, but you've already done this by calling your new `retrieveAndMerge` function from the talon. I am just proposing that we just call `removeCart` from the talon rather than from the action.

Once we get data back from `mergeCart` we can then also pass that to an action for storing in redux.

Since we are planning on deprecating the old mini cart logic, most of the old actions will get obsoleted anyways so I want to avoid adding new logic there if possible.

File: packages/peregrine/lib/talons/CreateAccount/useCreateAccount.js [hunk 17]
```diff
@@ -77,32 +92,31 @@ export const useCreateAccount = props => {
...
-                await clearCustomerDataFromCache(apolloClient);
 
+                // Create and get the customer's cart id.
                 await createCart({
                     fetchCartId
                 });
+                const destinationCartId = await retrieveCartId();
```
Comment (sirugh) [inline packages/peregrine/lib/talons/CreateAccount/useCreateAccount.js:108]: This all works but I have concerns about directly fetching the cart id from local storage. It's a little magical in that it relies on the logic internal to `createCart` that actually calls the invoker and sets the response value in local storage and in redux. We _must_ make this call right now since the entire application relies on redux having a valid `cartId` at all times.

Ideally we could also return it from the action or maybe get `cartId` back from a query instead of reading from local storage. As we've found though, awaiting query invokers is not what ApolloGQL intended.

File: packages/peregrine/lib/talons/CreateAccount/useCreateAccount.js (hunk 12 above)
[the remark this answers is not in the document]
Comment (sirugh) [reply packages/peregrine/lib/talons/CreateAccount/useCreateAccount.js:99]: I added this back, but moved it above just before we call `removeCart`.

File: packages/peregrine/lib/talons/SignIn/useSignIn.js (hunk 10 above)
[the remark this answers is not in the document]
Comment (sirugh) [reply packages/peregrine/lib/talons/SignIn/useSignIn.js]: This is still done, just earlier in the callback.

File: packages/peregrine/lib/store/reducers/cart.js (hunk 1 above)
Comment (sirugh) [reply packages/peregrine/lib/store/reducers/cart.js]: Removed usage of actions.

File: packages/peregrine/lib/store/actions/cart/asyncActions.js (hunk 3 above)
Comment (sirugh) [reply packages/peregrine/lib/store/actions/cart/asyncActions.js]: Removed usage of redux.

File: packages/peregrine/lib/store/actions/cart/asyncActions.js (hunk 4 above)
Comment (sirugh) [reply packages/peregrine/lib/store/actions/cart/asyncActions.js]: Clarified with comments.

File: packages/peregrine/lib/store/actions/cart/asyncActions.js (hunk 7 above)
Comment (sirugh) [reply packages/peregrine/lib/store/actions/cart/asyncActions.js]: Removed usage of redux.

File: packages/peregrine/lib/store/actions/cart/asyncActions.js (hunk 8 above)
Comment (sirugh) [reply packages/peregrine/lib/store/actions/cart/asyncActions.js]: Removed usage of redux.

We still do call `removeCart` in the talon, but only to wipe redux of any stale cart data. Once we call `mergeCarts`, the new user's cart id will have all the info we need, so we then call `getCartDetails` and it updates the redux store. Eventually those calls won't be necessary since we will only be using GQL cache for rendering.

File: packages/peregrine/lib/store/reducers/cart.js [hunk 18]
```diff
@@ -28,6 +28,27 @@ const reducerMap = {
             cartId: String(payload)
         };
     },
+    [actions.mergeCarts.request]: state => {
+        return {
+            ...state,
+            isLoading: true
```
[the remark this answers is not in the document]
Comment (sirugh) [reply packages/peregrine/lib/store/reducers/cart.js]: Removed use of redux.

File: packages/peregrine/lib/store/actions/cart/asyncActions.js [hunk 19]
```diff
@@ -360,6 +360,50 @@ export const getCartDetails = payload => {
...
+
+            // errors can come from graphql and are not thrown
```
[the remark this answers is not in the document]
Comment (sirugh) [reply packages/peregrine/lib/store/actions/cart/asyncActions.js]: Removed use of redux, but this comment came from some other code that was copied. See createCart action.

File: packages/peregrine/lib/store/actions/cart/asyncActions.js (hunk 15 above)
[the remark this answers is not in the document]
Comment (sirugh) [reply packages/peregrine/lib/store/actions/cart/asyncActions.js]: Removed use of redux.

File: packages/peregrine/lib/talons/CreateAccount/useCreateAccount.js [hunk 20]
```diff
@@ -67,7 +74,15 @@ export const useCreateAccount = props => {
...
             setIsSubmitting(true);
             try {
-                // Try to create an account with the mutation.
+                // Get source cart id (guest cart id).
+                const sourceCartId = cartId;
+
+                // Clear all cart/customer data from cache and redux.
+                await clearCartDataFromCache(apolloClient);
+                await clearCustomerDataFromCache(apolloClient);
+                await removeCart();
```
Comment (sirugh) [inline packages/peregrine/lib/talons/CreateAccount/useCreateAccount.js:83]: We should consider being more graceful in handling errors during these callbacks. If an error happens during this workflow what happens to the user's old cart?

Comment (tjwiebell) [reply packages/peregrine/lib/talons/CreateAccount/useCreateAccount.js:83]: Ignore me, testing reviews in WebStorm; hopefully this isn't a comment.

File: packages/peregrine/lib/talons/CreateAccount/useCreateAccount.js (hunk 17 above)
Comment (tjwiebell) [reply packages/peregrine/lib/talons/CreateAccount/useCreateAccount.js:108]: I've been thinking a lot about getting away from this pattern of chaining, and I want your thoughts if this might clean this logic up, and get rid of the need to inject this into the current logic. This code could even live at a single place closer to the app root, no need to duplicate. Say it with me, react to state!

This is a bit mocked up, so deps are missing, sorry.
```js
const inititalCartId = useRef();

useEffect(() => {
    if (cartId && !inititalCartId.current) {
        inititalCartId.current = cartId;
    }
});

useEffect(() => {
    if (isSignedIn && cartId !== inititalCartId.current) {
        // merge those damn carts
        inititalCartId.current = cartId;
    }
});
```

There might be an edge here where an authenticated user just checked out, so you wouldn't want to attempt a merge, but I'm sure we could handle that. Consider this uber optional if you're looking for an alternative to fetching direct from localStorage.

File: packages/venia-ui/lib/components/CreateAccount/createAccount.js [hunk 21]
```diff
@@ -10,6 +10,7 @@ import CREATE_CART_MUTATION from '../../queries/createCart.graphql';
 import GET_CART_DETAILS_QUERY from '../../queries/getCartDetails.graphql';
 import GET_CUSTOMER_QUERY from '../../queries/getCustomer.graphql';
 import SIGN_IN_MUTATION from '../../queries/signIn.graphql';
+import { mergeCarts as MERGE_CARTS_MUTATION } from '../../queries/mergeCarts.gql';
```
Comment (tjwiebell) [inline packages/venia-ui/lib/components/CreateAccount/createAccount.js:13]: Should we just rename the export so you don't have to alias?

File: packages/venia-ui/lib/queries/mergeCarts.gql.js [hunk 22]
```diff
@@ -0,0 +1,39 @@
+import gql from 'graphql-tag';
+
+import { CartPageFragment } from '../components/CartPage/cartPageFragments.gql';
+import { CartTriggerFragment } from '../components/Header/cartTriggerFragments.gql';
+import { CheckoutPageFragment } from '../components/CheckoutPage/checkoutPageFragments.gql';
```
Comment (tjwiebell) [inline packages/venia-ui/lib/queries/mergeCarts.gql.js:5]: It's not great that this is needed; I almost typed that all queries mounted would re-fetch on the cartId change, but they wouldn't re-fetch on merge 😞  it would almost be preferable to wait to update cartId state until they've been merged, but that sounds very imbedded into those redux actions. Oof, very fragile, but can't think of an alternative until redux is out of the picture.

The only other quick solution I can think of is a page refresh, but this sounds preferable over that for now, and we can re-visit later.

File: packages/peregrine/lib/talons/CreateAccount/useCreateAccount.js [hunk 23]
```diff
@@ -3,8 +3,10 @@ import { useApolloClient, useMutation } from '@apollo/react-hooks';
 import { useUserContext } from '@magento/peregrine/lib/context/user';
 import { useCartContext } from '@magento/peregrine/lib/context/cart';
 import { useAwaitQuery } from '@magento/peregrine/lib/hooks/useAwaitQuery';
+
```
Comment (tjwiebell) [inline packages/peregrine/lib/talons/CreateAccount/useCreateAccount.js:6]: Consider fixing these imports to be relative while we're here.

File: packages/venia-ui/lib/queries/mergeCarts.gql.js [hunk 24]
```diff
@@ -0,0 +1,39 @@
...
+
+export const mergeCarts = gql`
```
Comment (tjwiebell) [inline packages/venia-ui/lib/queries/mergeCarts.gql.js:7]: Mentioned elsewhere, but consider renaming this to follow our normal convention (assuming all caps constant style is our convention).

```suggestion
export const MERGE_CARTS = gql`
```

File: packages/venia-ui/lib/components/CreateAccount/createAccount.js (hunk 21 above)
Comment (sirugh) [reply packages/venia-ui/lib/components/CreateAccount/createAccount.js:13]: heh, yes.

File: packages/peregrine/lib/talons/CreateAccount/useCreateAccount.js (hunk 23 above)
Comment (sirugh) [reply packages/peregrine/lib/talons/CreateAccount/useCreateAccount.js:6]: Will do.

File: packages/venia-ui/lib/queries/mergeCarts.gql.js (hunk 24 above)
Comment (sirugh) [reply packages/venia-ui/lib/queries/mergeCarts.gql.js:7]: I'll rename it to something more inline with the other gql exports like `mergeCartMutation`.

File: packages/peregrine/lib/talons/CreateAccount/useCreateAccount.js (hunk 20 above)
Comment (sirugh) [reply packages/peregrine/lib/talons/CreateAccount/useCreateAccount.js:83]: > I would want to restore the old cartId if possible.

But by the time we've caught an error we've already removed the guest cart data from redux. We would need a way to provide a local cart id (`sourceCartId` here) to redux. Maybe all we need to do is add the param to the `getCartDetails` action?

File: packages/peregrine/lib/talons/CheckoutPage/OrderConfirmationPage/useCreateAccount.js [hunk 25]
```diff
@@ -69,7 +73,15 @@ export const useCreateAccount = props => {
         async formValues => {
             setIsSubmitting(true);
             try {
-                // Try to create an account with the mutation.
+                // Get source cart id (guest cart id).
+                const sourceCartId = cartId;
+
+                // Clear all cart/customer data from cache and redux.
+                await clearCartDataFromCache(apolloClient);
+                await clearCustomerDataFromCache(apolloClient);
```
[the remark this answers is not in the document]
Comment (sirugh) [reply packages/peregrine/lib/talons/CheckoutPage/OrderConfirmationPage/useCreateAccount.js:81]: Ah yes, I had just copied this callback from the other talon. If you're on the order confirmation page and creating an account the old cart data should have already been cleaned up.

It looks like we do [remove cart data](https://github.com/magento/pwa-studio/blob/develop/packages/peregrine/lib/talons/CheckoutPage/useCheckoutPage.js#L168) but we don't clean up customer data. Perhaps I should add it?

File: packages/peregrine/lib/talons/CreateAccount/useCreateAccount.js (hunk 17 above)
Comment (sirugh) [reply packages/peregrine/lib/talons/CreateAccount/useCreateAccount.js:108]: >There might be an edge here where an authenticated user just checked out, so you wouldn't want to attempt a merge, but I'm sure we could handle that

I also think that we're going to have a tough time doing this with the current retry logic in redux. I'd rather revisit this later once we've deprecated the redux cart slice.

> This code could even live at a single place closer to the app root, no need to duplicate.

This. I would love to have the cart context own the code for handling cart creation and merging.

File: packages/peregrine/lib/talons/CreateAccount/useCreateAccount.js (hunk 20 above)
Comment (tjwiebell) [reply packages/peregrine/lib/talons/CreateAccount/useCreateAccount.js:83]: Could you manually write the cartId back to localStorage then call `getCartDetails`? Not sure if that would actually update the store though.

Comment (sirugh) [reply packages/peregrine/lib/talons/CreateAccount/useCreateAccount.js:83]: No, `getCartDetails` reads from redux state, not from local storage. The only thing that reads cart id from local storage is `createCart`, and only if there is no cart id in the store.

Comment (sirugh) [reply packages/peregrine/lib/talons/CreateAccount/useCreateAccount.js:83]: I've addressed this by moving the stale data clearing to after the sign in or create account invocations. Once they resolve we can assume we should proceed with removal and with fetching/merging the user's cart.

File: packages/peregrine/lib/talons/CheckoutPage/OrderConfirmationPage/useCreateAccount.js (hunk 25 above)
[the remark this answers is not in the document]
Comment (sirugh) [reply packages/peregrine/lib/talons/CheckoutPage/OrderConfirmationPage/useCreateAccount.js]: Moved to the place order effect.

File: packages/peregrine/lib/talons/CheckoutPage/OrderConfirmationPage/useCreateAccount.js [hunk 26]
```diff
@@ -79,32 +77,25 @@ export const useCreateAccount = props => {
...
-                const token =
-                    response && response.data.generateCustomerToken.token;
-
+                const token = signInResponse.data.generateCustomerToken.token;
                 await setToken(token);
-                await getUserDetails({ fetchUserDetails });
 
-                // Then remove the old guest cart and get the cart id from gql.
-                // TODO: This logic may be replacable with mergeCart in 2.3.4
+                // Clear guest cart cart from redux.
```
Comment (supernova-at) [inline packages/peregrine/lib/talons/CheckoutPage/OrderConfirmationPage/useCreateAccount.js:89]:
```suggestion
                // Clear guest cart from redux.
```

File: packages/peregrine/lib/talons/CheckoutPage/OrderConfirmationPage/useCreateAccount.js [hunk 27]
```diff
@@ -79,32 +77,25 @@ export const useCreateAccount = props => {
...
-                await clearCartDataFromCache(apolloClient);
-                await clearCustomerDataFromCache(apolloClient);
-
+                // Create a new customer cart.
                 await createCart({
                     fetchCartId
                 });
 
+                // Ensure old stores are updated with any new data.
+                await getUserDetails({ fetchUserDetails });
```
Comment (supernova-at) [inline packages/peregrine/lib/talons/CheckoutPage/OrderConfirmationPage/useCreateAccount.js:98]: There's no `mergeCarts` operation here because the old "guest" cart will have just been ordered / wiped out, right?

File: packages/peregrine/lib/talons/CheckoutPage/useCheckoutPage.js [hunk 28]
```diff
@@ -163,9 +164,10 @@ export const useCheckoutPage = props => {
                     }
                 });
 
+                // Cleanup stale cart and customer info.
                 await removeCart();
-
                 await clearCartDataFromCache(apolloClient);
+                await clearCustomerDataFromCache(apolloClient);
```
Comment (supernova-at) [inline packages/peregrine/lib/talons/CheckoutPage/useCheckoutPage.js:170]: Was a bit surprised to see this - what customer data needs cleaned up after checkout? Wouldn't it remain the same?

File: packages/peregrine/lib/talons/Header/useCartTrigger.js [hunk 29]
```diff
@@ -32,18 +33,9 @@ export const useCartTrigger = props => {
...
-                variables: {
-                    cartId
-                }
-            });
-        }
-    }, [cartId, getItemCount]);
-
     const handleClick = useCallback(async () => {
         toggleDrawer('cart');
+        // TODO: Cart details should be fetched by MiniCart.
```
Comment (supernova-at) [inline packages/peregrine/lib/talons/Header/useCartTrigger.js:38]: 💯

File: packages/peregrine/lib/talons/SignIn/useSignIn.js [hunk 30]
```diff
@@ -47,48 +56,59 @@ export const useSignIn = props => {
...
+                    variables: {
+                        destinationCartId,
+                        sourceCartId
+                    }
+                });
 
-                await getCartDetails({ fetchCartId, fetchCartDetails });
+                // Ensure old stores are updated with any new data.
+                getUserDetails({ fetchUserDetails });
+                getCartDetails({ fetchCartId, fetchCartDetails });
```
Comment (supernova-at) [inline packages/peregrine/lib/talons/SignIn/useSignIn.js:90]: We've got this same web of code in a few different places now.

That said, I don't think it's worth refactoring because the talons are so specific. Just pointing out that it'll be easy for these to get out of sync and bugs to creep in.

File: packages/venia-ui/lib/components/SignIn/__tests__/signIn.spec.js [hunk 31]
```diff
@@ -114,7 +114,8 @@ test('displays an error message if there is a sign in error', () => {
     expect(component.toJSON()).toMatchSnapshot();
 });
 
-test('calls `signIn` on submit', () => {
+// TODO: Move this to useSignIn.spec.js and test handleSignIn
+test.skip('calls `signIn` on submit', () => {
```
Comment (supernova-at) [inline packages/venia-ui/lib/components/SignIn/__tests__/signIn.spec.js:118]: Are you tackling this in this PR? 
If not, mind creating a ticket for it?

File: packages/peregrine/lib/talons/CheckoutPage/OrderConfirmationPage/useCreateAccount.js (hunk 27 above)
Comment (sirugh) [reply packages/peregrine/lib/talons/CheckoutPage/OrderConfirmationPage/useCreateAccount.js:98]: Yes - I had originally added it in the PR but realized there was no need to do that. If you create an account on the order confirmation page, you're doing so with zero items in your guest cart.

File: packages/peregrine/lib/talons/CheckoutPage/useCheckoutPage.js (hunk 28 above)
Comment (sirugh) [reply packages/peregrine/lib/talons/CheckoutPage/useCheckoutPage.js:170]: Hmm maybe this should be removed - I thought it was necessary but if we have customer data it's only for a logged in user and we don't need to clear that on checkout.

File: packages/peregrine/lib/talons/SignIn/useSignIn.js (hunk 30 above)
Comment (sirugh) [reply packages/peregrine/lib/talons/SignIn/useSignIn.js:90]: Not worth refactoring - we will be removing a lot of this when we do the work on new mini cart.

File: packages/venia-ui/lib/components/SignIn/__tests__/signIn.spec.js (hunk 31 above)
Comment (sirugh) [reply packages/venia-ui/lib/components/SignIn/__tests__/signIn.spec.js:118]: Do we make tickets for writing tests?

Comment (sirugh) [reply packages/venia-ui/lib/components/SignIn/__tests__/signIn.spec.js:118]: https://jira.corp.magento.com/browse/PWA-700

Comment (supernova-at) [reply packages/venia-ui/lib/components/SignIn/__tests__/signIn.spec.js:118]: > Do we make tickets for writing tests?

Lol fair enough. Thanks :)

**Comment by dpatil-magento** [comment]
Cart product merging is looking good. Some Observations :
1. Gift Options applied in guest cart does not carry over to Auth.
2. If Auth already has Gift card (xyz) added and Guest has new gift card (abc) added, then on login Guest giftcard (abc) is applied but Auth Gift card (xyz) is removed.
3. If Auth has coupon applied, then Guest Coupon has priority over Auth coupon. (Hope this is fine)

**Comment by sirugh** [comment]
Wow @dpatil-magento you always amaze me with what you can find :)

> Gift Options applied in guest cart does not carry over to Auth.

AFAIK gift options aren't live in GQL which means they are purely visual. We could spend effort to carry over the state of the cache between guest/auth but that might be more trouble than it's worth. Personally I'd rather just hide the gift options, or log this as a known issue that hopefully will get resolved when gift options are available through GQL.

> If Auth already has Gift card (xyz) added and Guest has new gift card (abc) added, then on login Guest giftcard (abc) is applied but Auth Gift card (xyz) is removed.

Interesting - I know that the guest GC was applied to the auth cart but I didn't know it removes an existing card. This is especially odd because you are allowed to have more than one GC on a cart. This feels like a GQL server issue but I want to check one thing - can you perform this test with gift cards that do not cover the entire balance? Say $100 cart total and $40/$40 GCs?

> If Auth has coupon applied, then Guest Coupon has priority over Auth coupon. (Hope this is fine)

You can only have one coupon applied to a cart, and going from guest to auth indicates you more recently applied the guest coupon. I don't think this is an issue but we should double check. @awilcoxa and @nrkapoor, can ya'll speak to this last point?

**Comment by dani97** [comment]
Thanks pwa studio team.

**Comment by ajithAllure** [comment]
Hi Im a magento 2 pwa developer can any one give link to some documentation or instructions to fix this issue in 12.3.0 pwa-studio magento 2.4.5
