### PR TITLE
Fixed #2426 Error if product is out of stock

### LINKED ISSUE #2426: Error if product is out of stock
**Describe the bug**
Error if product is out of stock

**To reproduce**
1. Go to Product Page of any out of stock product
2. Make sure in magento backend the below setting is set to `NO` 
    Store->Configuration->Catalog->Inventory->Display Out of Stock Products
3. Error on Product Page 

**Expected behavior**
It should show message `This Product is currently out of stock. Please try again later.` as set in root Component

**Screenshots**
image

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]: PC
 - OS [e.g. iOS8.1, Windows 10]: Linux
 - Browser [e.g. Chrome, Safari]: Chrome
 - Browser Version [e.g. 22]: 83
 - Magento Version: 2.3.5
 - PWA Studio Version: 6
 - NPM version `npm -v`: 6.4.1
 - Node Version `node -v`: 10.15.3

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

### PR DESCRIPTION
**Pull request by shikhamis11**
## Description

Fixed #2426 Error if product is out of stock

## Related Issue

Closes #2426

### Verification Steps

1. Go to Product Page of any out of stock product
2. Make sure in magento backend the below setting is set to `NO` 
    Store->Configuration->Catalog->Inventory->Display Out of Stock Products
3. Error on Product Page 

## Screenshots / Screen Captures (if appropriate)
image

## Checklist

* I have updated the documentation accordingly, if necessary.
[ ] I have added tests to cover my changes, if necessary.

### CODE REVIEW

**Comment by devops-pwa-codebuild** [comment]
**Performance Test Results**

The following fails have been reported by WebpageTest. These numbers indicates a possible performance issue with the PR which requires further manual testing to validate.

https://pr-2427.pwa-venia.com : LH Performance Expected 0.85 Actual 0.58, LH Best Practices Expected 1 Actual 0.92
https://pr-2427.pwa-venia.com/venia-tops.html : LH Performance Expected 0.75 Actual 0.35, LH Best Practices Expected 1 Actual 0.92
https://pr-2427.pwa-venia.com/valeria-two-layer-tank.html : LH Performance Expected 0.8 Actual 0.5, LH Accessibility Expected 0.9 Actual 0.89, LH Best Practices Expected 1 Actual 0.92

File: packages/peregrine/lib/talons/RootComponents/Product/useProduct.js [hunk 1]
```diff
@@ -72,7 +72,7 @@ export const useProduct = props => {
             return mapProduct(productFromCache);
         }
 
-        if (data) {
+        if (data && data.productDetail.items[0]) {
```
Comment (sirugh) [inline packages/peregrine/lib/talons/RootComponents/Product/useProduct.js:75]: What is the case where we have data but not `data.productDetail`?
