### PR TITLE
#2441: Fix for Category Sort

### LINKED ISSUE #2441: [bug]: ProductSort/CategorySort component shouldn't be conditional on filters being present
**Describe the bug**
The `ProductSort`/`CategorySort` component (it seems to have had a name change recently?) is rendered in a `.headerButtons` container, which is defined in `venia-ui/lib/RootComponents/Category/categoryContent.js` on line 44. This means that if there are no filters available, then sorting is also unavailable.

This appears to be left over logic from when the only header button was a Filters toggle button. At that point it made sense to make the header buttons conditional on there actually being filters to toggle, but now that a sort by button is in there, I don't think it makes sense anymore

**To reproduce**
1. Open `venia-ui/lib/RootComponents/Category/categoryContent.js` on line 44. This means that if there are no filters available, then sorting is also unavailable.`
2. Remove `filters` from the `talonProps` destructure
3. Add `const filters = false;` to the line directly under the `talonProps` destructure
4. Load up app
5. See that not only the Filters toggle button is removed, but also the sort by button

N.b. Obviously this is hacking the code to force a certain situation, but I figured it's the easiest way to demonstrate, rather than having to modify the BE in order to remove all filters

**Expected behavior**
When there aren't any filters available, then _only_ the Filters toggle button should be hidden

**Screenshots**
Filters disabled
image

Filters enabled
image

**Possible solutions**
Instead of wrapping the entirety of the header buttons in a conditional check on `filters`, _only_ the Filters toggle button should be.

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]: All
 - OS [e.g. iOS8.1, Windows 10]: All
 - Browser [e.g. Chrome, Safari]: All
 - Browser Version [e.g. 22]: All
 - Magento Version: All
 - PWA Studio Version: 6
 - NPM version `npm -v`: All
 - Node Version `node -v`: All

**Please let us know what packages this bug is in regards to:**
- [*] `venia-ui`

### PR DESCRIPTION
**Pull request by larsroettig**
## Description
- Fix will sort only show Category page with filters
- Fix Sort will show on category page without products 

## Related Issue
Closes #2441

### Verification Steps

1. Go any Category Page sort will display
2. Go on Category Page without products sort will not be shown 

## Checklist

- [x] I have added tests to cover my changes, if necessary.
- [x] I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by devops-pwa-codebuild** [comment]
**Performance Test Results**

The following fails have been reported by WebpageTest. These numbers indicates a possible performance issue with the PR which requires further manual testing to validate.

https://pr-2493.pwa-venia.com : LH Performance Expected 0.85 Actual 0.57, LH Best Practices Expected 1 Actual 0.92
https://pr-2493.pwa-venia.com/venia-tops.html : LH Performance Expected 0.75 Actual 0.35, LH Best Practices Expected 1 Actual 0.92
https://pr-2493.pwa-venia.com/valeria-two-layer-tank.html : LH Performance Expected 0.8 Actual 0.5, LH Accessibility Expected 0.9 Actual 0.89, LH Best Practices Expected 1 Actual 0.92

File: packages/venia-ui/lib/RootComponents/Category/categoryContent.js [hunk 1]
```diff
@@ -41,26 +41,30 @@ const CategoryContent = props => {
...
+            className={classes.filterButton}
+            onClick={handleOpenFilters}
+            onFocus={handleLoadFilters}
+            onMouseOver={handleLoadFilters}
+            type="button"
+        >
+            {'Filter'}
+        </button>
+    ) : (
+        ''
```
Comment (sirugh) [inline packages/venia-ui/lib/RootComponents/Category/categoryContent.js:55]: Instead of returning an empty string just return `null`.

File: packages/venia-ui/lib/RootComponents/Category/categoryContent.js [hunk 2]
```diff
@@ -41,26 +41,28 @@ const CategoryContent = props => {
...
+            onFocus={handleLoadFilters}
+            onMouseOver={handleLoadFilters}
+            type="button"
+        >
+            {'Filter'}
+        </button>
+    ) : null;
+
+    const maybeSortButton =
+        totalPagesFromData !== 0 ? <ProductSort sortProps={sortProps} /> : null;
```
Comment (tjwiebell) [inline packages/venia-ui/lib/RootComponents/Category/categoryContent.js:57]: This prop can also be `null`, so lets just do a truthy check:

```suggestion
        totalPagesFromData ? <ProductSort sortProps={sortProps} /> : null;
```

File: packages/venia-ui/lib/RootComponents/Category/categoryContent.js [hunk 3]
```diff
@@ -41,26 +41,28 @@ const CategoryContent = props => {
...
+
+    const maybeSortContainer =
+        totalPagesFromData !== 0 ? (
```
Comment (tjwiebell) [inline packages/venia-ui/lib/RootComponents/Category/categoryContent.js:60]:
```suggestion
        totalPagesFromData ? (
```

**Comment by tjwiebell** [comment]
@larsroettig - Any objection if we take this over internally? You've completed 95% of it, so we're happy to help fill in the 5% of tests to get this merged.

**Comment by larsroettig** [comment]
> Looks good, nice work  Love it when writing a test uncovers a bug, thanks for fixing that up as well.
> 
> The snapshot updates to `giftCards.spec.js` is causing builds to fail, so I'm probably going to revert that and push this to QA. Let's catch up on Slack with what your local setup is, and why that was needed for you to get green builds locally.

Maybee my Node Verison I get new Laptop last week and need to setup a toolchain as my old again. But got cached I will check it.

**Comment by dpatil-magento** [comment]
QA Approved.
