### PR TITLE
[Fix bug] Category didn't refresh data when click back previous or next page of…

### LINKED ISSUE #2638: [bug]: Category didn't refresh data when click back previous or next page of browser
**Describe the bug**
Click to an category have more than 1 page in left navigation, then click to page 2 of this category. After that, click to back on browser (not at pagination at bottom)
Screen Shot 2020-08-18 at 12 00 54 PM
The data of page 1 is not loaded.

**To reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Possible solutions**
Add any ideas about possible solutions to the problem here.

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]:
 - OS [e.g. iOS8.1, Windows 10]:
 - Browser [e.g. Chrome, Safari]:
 - Browser Version [e.g. 22]: Chrome Version 84.0.4147.125
 - Magento Version:
 - PWA Studio Version:
 - NPM version `npm -v`:
 - Node Version `node -v`:

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

### PR DESCRIPTION
**Pull request by huykon**
## Description

This PR to resolve : Category didn't refresh data when click back previous or next page of browser

## Related Issue

Closes #2638.

### Verification Steps

1. Go to category Dresses on left menu bar.
2. Go to page 2.
3. Click to back button of browser.
4. The data of page 1 reloaded.

## Checklist

- [ ] I have added tests to cover my changes, if necessary.
* I have updated the documentation accordingly, if necessary.

### CODE REVIEW

File: packages/peregrine/lib/hooks/usePagination.js [hunk 1]
```diff
@@ -73,6 +73,12 @@ export const usePagination = (props = {}) => {
         [history, location, searchParam]
     );
 
+    useMemo(() => {
+        if (initialPage && initialPage !== currentPage) {
+            setCurrentPage(initialPage);
+        }
+    }, [initialPage, currentPage]);
```
Comment (sirugh) [inline packages/peregrine/lib/hooks/usePagination.js:80]: For starters let's use `useEffect` instead of `useMemo`. While memoization has a side effect of invoking the callback, the effect hook is more appropriate here. And because `initialPage` is always truthy (it has a default value fallback) you can skip the truthy check.

```
    useEffect(() => {
        if (initialPage !== currentPage) {
            setCurrentPage(initialPage);
        }
    }, [currentPage, initialPage]);
```

I was wondering though why we would want to call `setCurrentPage` directly and not use the `setPage` callback.

Comment (huykon) [reply packages/peregrine/lib/hooks/usePagination.js]: I have just updated code use `useEffect`. I have to use directly `setCurrentPage ` cause your `setPage` callback will reset param on URL, that mean when you back from page 2 to page 1 then you could not click next to page 2 although page 2 data was loaded.

**Comment by supernova-at** [comment]
> Adds unit tests for usePagination hook (f14e077)

Comically, this doesn't include a test for your effect. It's a tricky one to get at, I'll re-visit when I get some more time.

**Comment by huykon** [comment]
@supernova-at can you help me done this test case?

**Review by jimbo — APPROVED** [review]

**Review by jimbo — CHANGES_REQUESTED** [review]
Well, my earlier approval was premature. The fix you've proposed is simple, and it does indeed solve the issue it purports to address. Unfortunately, it may introduce a new bug, so let's see if we can refine it.

Generally, it should be a red flag whenever you're trying to take new props and write them to state. One or the other should be the source of truth, and if you're keeping local state, it should generally be local state. Otherwise, this introduces an issue where stale props will overwrite the more volatile local state.

The only reason this bug _isn't_ manifesting here is because [`Category` doesn't pass `initialPage` to `usePagination`](https://github.com/magento/pwa-studio/blob/develop/packages/venia-ui/lib/RootComponents/Category/category.js#L24). If it did, pagination would break, because every time the user advanced `currentPage` from `1` to `2` (in both local state and the URL), the effect you've added here would reset it to `1`. That is, the effect would notice the disparity between props and local state, and it would reset local state to the stale value of `props.initialPage`.

Fortunately, it works well to update local state when the URL changes, which is what's making this PR work right now. I think we just need to refine how we use `props.initialPage` so that we only use it to seed local state and the URL. From that point, we can ignore props and adjust the effect to only watch for disparity between the URL and local state.

Anyway, I've updated the tests to cover the effect. Hopefully it helps illustrate how we can test effects and what assertions we want to be able to make about them. 😅

**Comment by huykon** [comment]
Hi @jimbo Thanks for your comment. I though the problem was resolved but not. So How can I do anything to resolve this PR?

**Review by jimbo — DISMISSED** [review]

**Comment by jimbo** [comment]
Thanks for pushing changes. This is approved from my end, as long as CI is passing.

**Comment by supernova-at** [comment]
There is a comment in the unit tests that says

> // second call is inaccurate. this assertion should fail

This looks like a "note to self" kind of comment; we shouldn't be including assertions that should fail (there is a `not` operator for that).
But at the same time the tests seem to have passed, so... 🤷‍♂️

**Comment by huykon** [comment]
so what problem with this test case?

**Review by jimbo — DISMISSED** [review]
Ah, thanks for merging my PR. I'll be more comfortable with this fix now that we've eliminated some of the re-renders. 👍

**Comment by dpatil-magento** [comment]
@huykon @jimbo Traverse path  Home > Category - Page 1 > Page -2 . Now start hitting back button from page 2, it works only till page 1, after that browser back is not functioning, user is stuck on Page 1 irrespective of how many timed browser back button is clicked.

Expected - In above scenario Page 1 > Home page back path should also work.

<a href="https://gyazo.com/d2d63c14a4e5fd9e73366d5b213d383c">Image from Gyazo</a>

**Review by tjwiebell — APPROVED** [review]
Fix looks good, consider updating the function comment but not blocking an approval 👍

**Comment by dpatil-magento** [comment]
QA Approved.

**Comment by huykon** [comment]
Look good now. Thank @jimbo very much for support and make sense for me

**Review by dpatil-magento — APPROVED** [review]
Approved latest commit.
