### PR TITLE
[#2141] Fix wrong PriceSummaryQuery export

### LINKED ISSUE #2141: export 'PriceSummaryQuery' was not found in './priceSummary'
**Describe the bug**
Console issues when I run `yarn watch:venia`

**To reproduce**
1. Clone last version of develop
2. Just run `yarn watch:venia`
3. See warning: 

```bash
    WARNING in ../venia-ui/lib/components/CartPage/PriceSummary/index.js 5:0-60
    "export 'PriceSummaryQuery' was not found in './priceSummary'
     @ ../venia-ui/lib/components/CartPage/cartPage.js
     @ ../venia-ui/lib/components/CartPage/index.js
     @ ../venia-ui/lib/components/Routes/routes.js
     @ ../venia-ui/lib/components/Routes/index.js
     @ ../venia-ui/lib/components/App/app.js
     @ ../venia-ui/lib/components/App/container.js
     @ ../venia-ui/lib/components/App/index.js
     @ ./src/index.js
     @ multi (webpack)-dev-server/client?https://nymansur.local:8258 (webpack)/hot/dev-server.js (webpack)-inject-plugin/dist/webpack-inject-plugin.loader?id=webpack-inject-module-1 ./src/index.js
```

**Expected behavior**

I expect that current version of develop is working without the issues in console.

**Additional context**
Issue source - > https://github.com/magento/pwa-studio/commit/0d72488ec52ebcac6d0b39d0e89e0644cc47ad39#diff-e61cf7f7d83179045a0aab880694b1caL102 

**Possible solutions**
Add any ideas about possible solutions to the problem here.

**Please complete the following device information:**
 - Device Mac
 - OS Catalina 10.15.2
 - Browser Chrome 
 - Browser Version  79.0.3945.130
 - Magento Version: 
 - PWA Studio Version: develop
 - NPM version 6.13.4
 - Node Version v10.18.0

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

### PR DESCRIPTION
**Pull request by mercs600**
## Description

It fixes wrong export (https://github.com/magento/pwa-studio/issues/2141) 

## Related Issue

closes #2141.

### Verification Stakeholders
@sirugh 

### Verification Steps

1. Clone this PR
2. Just run yarn watch:venia
3. You won't see warning in console

### CODE REVIEW

File: packages/venia-ui/lib/components/CartPage/PriceSummary/index.js [hunk 1]
```diff
@@ -1 +1 @@
-export { default, PriceSummaryQuery } from './priceSummary';
+export { default, GET_PRICE_SUMMARY } from './priceSummary';
```
Comment (sirugh) [inline packages/venia-ui/lib/components/CartPage/PriceSummary/index.js]: Ah I meant to actually remove this export from `priceSummary.js`. Can you just remove the export from line 102 of that file, move the query _above_ the component, and then remove the export here? Thanks!

Comment (mercs600) [reply packages/venia-ui/lib/components/CartPage/PriceSummary/index.js]: Ok, I removed unused export and moved query above component.
